# Advanced SQL query syntax part 1 - WHERE


**Author:** 'Felipe Millacura'
    
**Date:** '14th March 2021'

### Learning Objectives


* Be able to use additional comparison operators, with `AND` and `OR` combinations
* Write queries using `BETWEEN`, `NOT` and `IN`
* Understand and be able to use inexact comparisons with `LIKE` and wildcards
* Understand `IS NULL`
* Be able to create column aliases using `AS`
* Use `DISTINCT` to return unique records by column
* Understand and be able to use aggregate functions
* Be able to sort records and `LIMIT` the number returned
* Understand `GROUP BY` and `HAVING` for group level aggregation and filtering



## Introduction

As stated earlier, a Data Analyst more often read records in databases than create, update or delete them (recall CRUD). So, it makes sense to focus effort on learning `SELECT` syntax beyond simple `WHERE` clauses. We’ll work through a series of examples, using the`dvd_rental` local `PostgreSQL` database we will set up in this lesson.

We’ll then come back to look at how we can manipulate the returned data from a query.


## The dataset

We will query the Sakila DVD Rental database. The Sakila Database holds information about a company that rents movie DVDs and it's a 15 tables demo dataset for [PostgreSQL](https://www.postgresqltutorial.com/postgresql-sample-database/) 

**Note:** One quirk you may notice as you explore this "fake" database is that the rental dates are all from 2005 and 2006, while the payment dates are all from 2007. Don't worry about this. 


To assist you in the queries ahead, the **Entity Relationship Diagram (ERD)** for the DVD Rental database is provided below. You can find further information about ERDs [here](https://www.smartdraw.com/entity-relationship-diagram/)

![](images/database_dvd.png)

## Setup 

First, we need to install PostgreSQL into our local machine (or using Udacity's workplace). The instructions differ from OS but you can find them here for [Windows](https://www.postgresqltutorial.com/install-postgresql/), [Mac](https://www.postgresqltutorial.com/install-postgresql-macos/) or [Linux](https://www.postgresqltutorial.com/install-postgresql-linux/) 

Once PostgreSQL has been properly installed you will need to follow some [additional steps](https://www.postgresqltutorial.com/connect-to-postgresql-database/) to *restore* your `dvd_rental` database 

Once installed, we need to establish a Python connection to the database. Remember that we need to use the *magic commands* to load the `ipython-sql` extension.

In [2]:
%load_ext sql


Optionally, you can create an engine for later use using `sqlalchemy`'s `create_engine` 

In [ ]:
from sqlalchemy import create_engine

In [ ]:
# default
engine = create_engine('postgresql://postgres:trialpostgres@localhost/dvdrental')


This allows you to store SQL queries results directly in a pandas DataFrame by using [`pd.read_sql()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_sql.html)

In [ ]:
import pandas as pd

In [ ]:
df_customer = pd.read_sql('SELECT some_column FROM some_table', engine)

df_customer.head(4)

# Connecting to a PostgreSQL database

To connect `ipython-sql` to your database use the following format:

```python
# Format
%sql dialect+driver://username:password@host:port/database
# Example
%sql postgresql://postgres:password123@localhost/dvdrental
            
```          




* `dialect+driver` in this case would just be `postgresql`, but feel free to use a different database software here.
* `username:password` is where you will substitute your username and password.
* `host` is usually just localhost.
* `port` does not need to be specified most of the time.
* `database` is the name of the database to connect to.

In [3]:
%sql  postgresql://postgres:trialpostgres@localhost/dvdrental

Now we are ready to work with our DataBase

In [4]:
%sql SELECT * FROM actor

 * postgresql://postgres:***@localhost/dvdrental
200 rows affected.


[(1, 'Penelope', 'Guiness', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (2, 'Nick', 'Wahlberg', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (3, 'Ed', 'Chase', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (4, 'Jennifer', 'Davis', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (5, 'Johnny', 'Lollobrigida', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (6, 'Bette', 'Nicholson', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (7, 'Grace', 'Mostel', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (8, 'Matthew', 'Johansson', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (9, 'Joe', 'Swank', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (10, 'Christian', 'Gable', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (11, 'Zero', 'Cage', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (12, 'Karl', 'Berry', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (13, 'Uma', 'Wood', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (14, 'Vivien', 'Bergen', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (15, 'Cuba', 'Olivier', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (16, 'Fred', 'Costner', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (17, 'Helen', 'Voight', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (18, 'Dan', 'Torn', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (19, 'Bob', 'Fawcett', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (20, 'Lucille', 'Tracy', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (21, 'Kirsten', 'Paltrow', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (22, 'Elvis', 'Marx', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (23, 'Sandra', 'Kilmer', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (24, 'Cameron', 'Streep', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (25, 'Kevin', 'Bloom', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (26, 'Rip', 'Crawford', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (27, 'Julia', 'Mcqueen', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (28, 'Woody', 'Hoffman', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (29, 'Alec', 'Wayne', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (30, 'Sandra', 'Peck', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (31, 'Sissy', 'Sobieski', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (32, 'Tim', 'Hackman', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (33, 'Milla', 'Peck', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (34, 'Audrey', 'Olivier', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (35, 'Judy', 'Dean', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (36, 'Burt', 'Dukakis', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (37, 'Val', 'Bolger', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (38, 'Tom', 'Mckellen', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (39, 'Goldie', 'Brody', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (40, 'Johnny', 'Cage', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (41, 'Jodie', 'Degeneres', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (42, 'Tom', 'Miranda', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (43, 'Kirk', 'Jovovich', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (44, 'Nick', 'Stallone', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (45, 'Reese', 'Kilmer', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (46, 'Parker', 'Goldberg', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (47, 'Julia', 'Barrymore', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (48, 'Frances', 'Day-Lewis', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (49, 'Anne', 'Cronyn', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (50, 'Natalie', 'Hopkins', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (51, 'Gary', 'Phoenix', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (52, 'Carm

## Simple `WHERE` clauses

So far we've seen pretty simple `WHERE` clauses, e.g. find the actor with `id` equal to 3.


In [5]:
%%sql 

SELECT * 
FROM actor 
WHERE actor_id = 3

 * postgresql://postgres:***@localhost/dvdrental
1 rows affected.


[(3, 'Ed', 'Chase', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000))]

# Additional comparison operators

OK, but what about this problem:<br>

> "Find all films with `rental_duration` 3 equivalent hours or less."

We can solve this using operators other than `=`


| operator | meaning |
| --- | --- |
| != | not equal to |
| > | greater than |
| < | less than |
| >= | greater than or equal to |
| <= | less than or equal to |

In [6]:
%%sql 

SELECT * 
FROM film 
WHERE rental_duration <= 3

 * postgresql://postgres:***@localhost/dvdrental
203 rows affected.


[(2, 'Ace Goldfinger', 'A Astounding Epistle of a Database Administrator And a Explorer who must Find a Car in Ancient China', 2006, 1, 3, Decimal('4.99'), 48, Decimal('12.99'), 'G', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Deleted Scenes'], "'ace':1 'administr':9 'ancient':19 'astound':4 'car':17 'china':20 'databas':8 'epistl':5 'explor':12 'find':15 'goldfing':2 'must':14"),
 (6, 'Agent Truman', 'A Intrepid Panorama of a Robot And a Boy who must Escape a Sumo Wrestler in Ancient China', 2006, 1, 3, Decimal('2.99'), 169, Decimal('17.99'), 'PG', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Deleted Scenes'], "'agent':1 'ancient':19 'boy':11 'china':20 'escap':14 'intrepid':4 'must':13 'panorama':5 'robot':8 'sumo':16 'truman':2 'wrestler':17"),
 (9, 'Alabama Devil', 'A Thoughtful Panorama of a Database Administrator And a Mad Scientist who must Outgun a Mad Scientist in A Jet Boat', 2006, 1, 3, Decimal('2.99'), 114, Decimal('21.99'), 'PG-13', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Deleted Scenes'], "'administr':9 'alabama':1 'boat':23 'databas':8 'devil':2 'jet':22 'mad':12,18 'must':15 'outgun':16 'panorama':5 'scientist':13,19 'thought':4"),
 (17, 'Alone Trip', 'A Fast-Paced Character Study of a Composer And a Dog who must Outgun a Boat in An Abandoned Fun House', 2006, 1, 3, Decimal('0.99'), 82, Decimal('14.99'), 'R', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Behind the Scenes'], "'abandon':22 'alon':1 'boat':19 'charact':7 'compos':11 'dog':14 'fast':5 'fast-pac':4 'fun':23 'hous':24 'must':16 'outgun':17 'pace':6 'studi':8 'trip':2"),
 (21, 'American Circus', 'A Insightful Drama of a Girl And a Astronaut who must Face a Database Administrator in A Shark Tank', 2006, 1, 3, Decimal('4.99'), 129, Decimal('17.99'), 'R', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Commentaries', 'Behind the Scenes'], "'administr':17 'american':1 'astronaut':11 'circus':2 'databas':16 'drama':5 'face':14 'girl':8 'insight':4 'must':13 'shark':20 'tank':21"),
 (23, 'Anaconda Confessions', 'A Lacklusture Display of a Dentist And a Dentist who must Fight a Girl in Australia', 2006, 1, 3, Decimal('0.99'), 92, Decimal('9.99'), 'R', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Deleted Scenes'], "'anaconda':1 'australia':18 'confess':2 'dentist':8,11 'display':5 'fight':14 'girl':16 'lacklustur':4 'must':13"),
 (25, 'Angels Life', 'A Thoughtful Display of a Woman And a Astronaut who must Battle a Robot in Berlin', 2006, 1, 3, Decimal('2.99'), 74, Decimal('15.99'), 'G', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers'], "'angel':1 'astronaut':11 'battl':14 'berlin':18 'display':5 'life':2 'must':13 'robot':16 'thought':4 'woman':8"),
 (26, 'Annie Identity', 'A Amazing Panorama of a Pastry Chef And a Boat who must Escape a Woman in An Abandoned Amusement Park', 2006, 1, 3, Decimal('0.99'), 86, Decimal('15.99'), 'G', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Commentaries', 'Deleted Scenes'], "'abandon':20 'amaz':4 'amus':21 'anni':1 'boat':12 'chef':9 'escap':15 'ident':2 'must':14 'panorama':5 'park':22 'pastri':8 'woman':17"),
 (37, 'Arizona Bang', 'A Brilliant Panorama of a Mad Scientist And a Mad Cow who must Meet a Pioneer in A Monastery', 2006, 1, 3, Decimal('2.99'), 121, Decimal('28.99'), 'PG', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Deleted Scenes'], "'arizona':1 'bang':2 'brilliant':4 'cow':13 'mad':8,12 'meet':16 'monasteri':21 'must':15 'panorama':5 'pioneer':18 'scientist':9"),
 (46, 'Autumn Crow', 'A Beautiful Tale of a Dentist And a Mad Cow who must Battle a Moose in The Sahara Desert', 2006, 1, 3, Decimal('4.99'), 108, Decimal('13.99'), 'G', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Commentaries', 'Deleted Scenes', 'Behind the Scenes'], "'autumn':1 'battl':15 'beauti':4 'cow':12 'crow':2 'dentist':8 'desert':21 'mad':11 'moos':17 'must':14 'sahara':2

<blockquote class='task'>

Task - 2 mins
<br>
    
Write and execute a query answering this problem:
<br>
  <br>  
<center>"Find all countries different than Brazil."</center>

<details>
<summary><b>Solution</b></summary>

 %%sql 
           SELECT * 
           FROM country 
           WHERE country != 'Brazil'

</details>
</blockquote>

In [8]:
%%sql

SELECT * 
FROM country
WHERE country != 'Brazil'

 * postgresql://postgres:***@localhost/dvdrental
108 rows affected.


[(1, 'Afghanistan', datetime.datetime(2006, 2, 15, 9, 44)),
 (2, 'Algeria', datetime.datetime(2006, 2, 15, 9, 44)),
 (3, 'American Samoa', datetime.datetime(2006, 2, 15, 9, 44)),
 (4, 'Angola', datetime.datetime(2006, 2, 15, 9, 44)),
 (5, 'Anguilla', datetime.datetime(2006, 2, 15, 9, 44)),
 (6, 'Argentina', datetime.datetime(2006, 2, 15, 9, 44)),
 (7, 'Armenia', datetime.datetime(2006, 2, 15, 9, 44)),
 (8, 'Australia', datetime.datetime(2006, 2, 15, 9, 44)),
 (9, 'Austria', datetime.datetime(2006, 2, 15, 9, 44)),
 (10, 'Azerbaijan', datetime.datetime(2006, 2, 15, 9, 44)),
 (11, 'Bahrain', datetime.datetime(2006, 2, 15, 9, 44)),
 (12, 'Bangladesh', datetime.datetime(2006, 2, 15, 9, 44)),
 (13, 'Belarus', datetime.datetime(2006, 2, 15, 9, 44)),
 (14, 'Bolivia', datetime.datetime(2006, 2, 15, 9, 44)),
 (16, 'Brunei', datetime.datetime(2006, 2, 15, 9, 44)),
 (17, 'Bulgaria', datetime.datetime(2006, 2, 15, 9, 44)),
 (18, 'Cambodia', datetime.datetime(2006, 2, 15, 9, 44)),
 (19, 'Cameroon', datetime.datetime(2006, 2, 15, 9, 44)),
 (20, 'Canada', datetime.datetime(2006, 2, 15, 9, 44)),
 (21, 'Chad', datetime.datetime(2006, 2, 15, 9, 44)),
 (22, 'Chile', datetime.datetime(2006, 2, 15, 9, 44)),
 (23, 'China', datetime.datetime(2006, 2, 15, 9, 44)),
 (24, 'Colombia', datetime.datetime(2006, 2, 15, 9, 44)),
 (25, 'Congo, The Democratic Republic of the', datetime.datetime(2006, 2, 15, 9, 44)),
 (26, 'Czech Republic', datetime.datetime(2006, 2, 15, 9, 44)),
 (27, 'Dominican Republic', datetime.datetime(2006, 2, 15, 9, 44)),
 (28, 'Ecuador', datetime.datetime(2006, 2, 15, 9, 44)),
 (29, 'Egypt', datetime.datetime(2006, 2, 15, 9, 44)),
 (30, 'Estonia', datetime.datetime(2006, 2, 15, 9, 44)),
 (31, 'Ethiopia', datetime.datetime(2006, 2, 15, 9, 44)),
 (32, 'Faroe Islands', datetime.datetime(2006, 2, 15, 9, 44)),
 (33, 'Finland', datetime.datetime(2006, 2, 15, 9, 44)),
 (34, 'France', datetime.datetime(2006, 2, 15, 9, 44)),
 (35, 'French Guiana', datetime.datetime(2006, 2, 15, 9, 44)),
 (36, 'French Polynesia', datetime.datetime(2006, 2, 15, 9, 44)),
 (37, 'Gambia', datetime.datetime(2006, 2, 15, 9, 44)),
 (38, 'Germany', datetime.datetime(2006, 2, 15, 9, 44)),
 (39, 'Greece', datetime.datetime(2006, 2, 15, 9, 44)),
 (40, 'Greenland', datetime.datetime(2006, 2, 15, 9, 44)),
 (41, 'Holy See (Vatican City State)', datetime.datetime(2006, 2, 15, 9, 44)),
 (42, 'Hong Kong', datetime.datetime(2006, 2, 15, 9, 44)),
 (43, 'Hungary', datetime.datetime(2006, 2, 15, 9, 44)),
 (44, 'India', datetime.datetime(2006, 2, 15, 9, 44)),
 (45, 'Indonesia', datetime.datetime(2006, 2, 15, 9, 44)),
 (46, 'Iran', datetime.datetime(2006, 2, 15, 9, 44)),
 (47, 'Iraq', datetime.datetime(2006, 2, 15, 9, 44)),
 (48, 'Israel', datetime.datetime(2006, 2, 15, 9, 44)),
 (49, 'Italy', datetime.datetime(2006, 2, 15, 9, 44)),
 (50, 'Japan', datetime.datetime(2006, 2, 15, 9, 44)),
 (51, 'Kazakstan', datetime.datetime(2006, 2, 15, 9, 44)),
 (52, 'Kenya', datetime.datetime(2006, 2, 15, 9, 44)),
 (53, 'Kuwait', datetime.datetime(2006, 2, 15, 9, 44)),
 (54, 'Latvia', datetime.datetime(2006, 2, 15, 9, 44)),
 (55, 'Liechtenstein', datetime.datetime(2006, 2, 15, 9, 44)),
 (56, 'Lithuania', datetime.datetime(2006, 2, 15, 9, 44)),
 (57, 'Madagascar', datetime.datetime(2006, 2, 15, 9, 44)),
 (58, 'Malawi', datetime.datetime(2006, 2, 15, 9, 44)),
 (59, 'Malaysia', datetime.datetime(2006, 2, 15, 9, 44)),
 (60, 'Mexico', datetime.datetime(2006, 2, 15, 9, 44)),
 (61, 'Moldova', datetime.datetime(2006, 2, 15, 9, 44)),
 (62, 'Morocco', datetime.datetime(2006, 2, 15, 9, 44)),
 (63, 'Mozambique', datetime.datetime(2006, 2, 15, 9, 44)),
 (64, 'Myanmar', datetime.datetime(2006, 2, 15, 9, 44)),
 (65, 'Nauru', datetime.datetime(2006, 2, 15, 9, 44)),
 (66, 'Nepal', datetime.datetime(2006, 2, 15, 9, 44)),
 (67, 'Netherlands', datetime.datetime(2006, 2, 15, 9, 44)),
 (68, 'New Zealand', datetime.datetime(2006, 2, 15, 9, 44)),
 (69, 'Nigeria', datetime.datetime(2006, 2, 15, 9, 44)),
 (70, 'North Korea', d

## `AND` and `OR` 

If required, we can create more complex clauses using the `AND` and `OR` operators

> "Find all films with `rental_rate` higher or equal than 4 and `rental_duration` higher than 3 hours".

%%sql

SELECT film_id, title, rental_rate, rental_duration
FROM film 
WHERE rental_rate >= 4 AND rental_duration > 3

In [9]:
%%sql

SELECT film_id, title, rental_rate, rental_duration
FROM film 
WHERE rental_rate >= 4 AND rental_duration > 3

 * postgresql://postgres:***@localhost/dvdrental
274 rows affected.


[(133, 'Chamber Italian', Decimal('4.99'), 7),
 (384, 'Grosse Wonderful', Decimal('4.99'), 5),
 (8, 'Airport Pollock', Decimal('4.99'), 6),
 (98, 'Bright Encounters', Decimal('4.99'), 4),
 (7, 'Airplane Sierra', Decimal('4.99'), 6),
 (10, 'Aladdin Calendar', Decimal('4.99'), 6),
 (13, 'Ali Forever', Decimal('4.99'), 4),
 (20, 'Amelie Hellfighters', Decimal('4.99'), 4),
 (28, 'Anthem Luke', Decimal('4.99'), 5),
 (31, 'Apache Divine', Decimal('4.99'), 5),
 (32, 'Apocalypse Flamingos', Decimal('4.99'), 6),
 (265, 'Dying Maker', Decimal('4.99'), 5),
 (44, 'Attacks Hate', Decimal('4.99'), 5),
 (45, 'Attraction Newton', Decimal('4.99'), 5),
 (47, 'Baby Hall', Decimal('4.99'), 5),
 (61, 'Beauty Grease', Decimal('4.99'), 5),
 (68, 'Betrayed Rear', Decimal('4.99'), 5),
 (70, 'Bikini Borrowers', Decimal('4.99'), 7),
 (74, 'Birch Antitrust', Decimal('4.99'), 4),
 (75, 'Bird Independence', Decimal('4.99'), 6),
 (77, 'Birds Perdition', Decimal('4.99'), 5),
 (81, 'Blindness Gun', Decimal('4.99'), 6),
 (84, 'Boiled Dares', Decimal('4.99'), 7),
 (86, 'Boogie Amelie', Decimal('4.99'), 6),
 (88, 'Born Spinal', Decimal('4.99'), 7),
 (92, 'Bowfinger Gables', Decimal('4.99'), 7),
 (93, 'Brannigan Sunrise', Decimal('4.99'), 4),
 (95, 'Breakfast Goldfinger', Decimal('4.99'), 5),
 (100, 'Brooklyn Desert', Decimal('4.99'), 7),
 (102, 'Bubble Grosse', Decimal('4.99'), 4),
 (103, 'Bucket Brotherhood', Decimal('4.99'), 7),
 (112, 'Calendar Gunfight', Decimal('4.99'), 4),
 (113, 'California Birds', Decimal('4.99'), 4),
 (117, 'Candles Grapes', Decimal('4.99'), 6),
 (123, 'Casablanca Super', Decimal('4.99'), 6),
 (127, 'Cat Coneheads', Decimal('4.99'), 5),
 (131, 'Center Dinosaur', Decimal('4.99'), 5),
 (134, 'Champion Flatliners', Decimal('4.99'), 4),
 (139, 'Chasing Fight', Decimal('4.99'), 7),
 (141, 'Chicago North', Decimal('4.99'), 6),
 (144, 'Chinatown Gladiator', Decimal('4.99'), 7),
 (145, 'Chisum Behavior', Decimal('4.99'), 5),
 (151, 'Cincinatti Whisperer', Decimal('4.99'), 5),
 (159, 'Closer Bang', Decimal('4.99'), 5),
 (161, 'Clue Grail', Decimal('4.99'), 6),
 (165, 'Coldblooded Darling', Decimal('4.99'), 7),
 (167, 'Coma Head', Decimal('4.99'), 6),
 (170, 'Command Darling', Decimal('4.99'), 5),
 (171, 'Commandments Express', Decimal('4.99'), 6),
 (172, 'Coneheads Smoochy', Decimal('4.99'), 7),
 (173, 'Confessions Maguire', Decimal('4.99'), 7),
 (174, 'Confidential Interview', Decimal('4.99'), 6),
 (177, 'Connecticut Tramp', Decimal('4.99'), 4),
 (179, 'Conquerer Nuts', Decimal('4.99'), 4),
 (182, 'Control Anthem', Decimal('4.99'), 7),
 (183, 'Conversation Downhill', Decimal('4.99'), 4),
 (190, 'Creepers Kane', Decimal('4.99'), 5),
 (192, 'Crossing Divorce', Decimal('4.99'), 4),
 (202, 'Daddy Pittsburgh', Decimal('4.99'), 5),
 (203, 'Daisy Menagerie', Decimal('4.99'), 5),
 (207, 'Dangerous Uptown', Decimal('4.99'), 7),
 (211, 'Darling Breaking', Decimal('4.99'), 7),
 (212, 'Darn Forrester', Decimal('4.99'), 7),
 (215, 'Dawn Pond', Decimal('4.99'), 4),
 (217, 'Dazed Punk', Decimal('4.99'), 6),
 (219, 'Deep Crusade', Decimal('4.99'), 6),
 (222, 'Desert Poseidon', Decimal('4.99'), 4),
 (224, 'Desperate Trainspotting', Decimal('4.99'), 7),
 (226, 'Destiny Saturday', Decimal('4.99'), 4),
 (227, 'Details Packer', Decimal('4.99'), 4),
 (229, 'Devil Desire', Decimal('4.99'), 6),
 (239, 'Dogma Family', Decimal('4.99'), 5),
 (244, 'Dorado Notting', Decimal('4.99'), 5),
 (246, 'Doubtfire Labyrinth', Decimal('4.99'), 5),
 (248, 'Dozen Lion', Decimal('4.99'), 6),
 (251, 'Dragonfly Strangers', Decimal('4.99'), 6),
 (253, 'Drifter Commandments', Decimal('4.99'), 5),
 (255, 'Driving Polish', Decimal('4.99'), 6),
 (256, 'Drop Waterfront', Decimal('4.99'), 6),
 (263, 'Durham Panky', Decimal('4.99'), 6),
 (267, 'Eagles Panky', Decimal('4.99'), 4),
 (268, 'Early Home', Decimal('4.99'), 6),
 (271, 'Easy Gladiator', Decimal('4.99'), 5),
 (272, 'Edge Kissing', Decimal('4.99'), 5),
 (276, 'Element Freddy', Decimal('4.99'), 6),
 (277, 'Elephant Trojan', Decimal('4.99')

Sometimes we have to be careful with the **order of evaluation** of conditions. Consider the following example


"Find all films with a `rental_rate` equal to 4.99 with either a `rental_duration` of 3 or lower or a `release_year` of 2006".



The logic of this as written is fairly clear. All the returned films should have a rating equal to 4.99 **and** they should either have been released on 2006 **or** or a have a rental duration of 3 or less!


In [10]:
%%sql

SELECT film_id, title, rental_rate, rental_duration, release_year
FROM film 
WHERE rental_rate = 4.99 AND rental_duration <= 3 OR release_year = 2006

 * postgresql://postgres:***@localhost/dvdrental
1000 rows affected.


[(133, 'Chamber Italian', Decimal('4.99'), 7, 2006),
 (384, 'Grosse Wonderful', Decimal('4.99'), 5, 2006),
 (8, 'Airport Pollock', Decimal('4.99'), 6, 2006),
 (98, 'Bright Encounters', Decimal('4.99'), 4, 2006),
 (1, 'Academy Dinosaur', Decimal('0.99'), 6, 2006),
 (2, 'Ace Goldfinger', Decimal('4.99'), 3, 2006),
 (3, 'Adaptation Holes', Decimal('2.99'), 7, 2006),
 (4, 'Affair Prejudice', Decimal('2.99'), 5, 2006),
 (5, 'African Egg', Decimal('2.99'), 6, 2006),
 (6, 'Agent Truman', Decimal('2.99'), 3, 2006),
 (7, 'Airplane Sierra', Decimal('4.99'), 6, 2006),
 (9, 'Alabama Devil', Decimal('2.99'), 3, 2006),
 (10, 'Aladdin Calendar', Decimal('4.99'), 6, 2006),
 (11, 'Alamo Videotape', Decimal('0.99'), 6, 2006),
 (12, 'Alaska Phantom', Decimal('0.99'), 6, 2006),
 (213, 'Date Speed', Decimal('0.99'), 4, 2006),
 (13, 'Ali Forever', Decimal('4.99'), 4, 2006),
 (14, 'Alice Fantasia', Decimal('0.99'), 6, 2006),
 (15, 'Alien Center', Decimal('2.99'), 5, 2006),
 (16, 'Alley Evolution', Decimal('2.99'), 6, 2006),
 (17, 'Alone Trip', Decimal('0.99'), 3, 2006),
 (18, 'Alter Victory', Decimal('0.99'), 6, 2006),
 (19, 'Amadeus Holy', Decimal('0.99'), 6, 2006),
 (20, 'Amelie Hellfighters', Decimal('4.99'), 4, 2006),
 (21, 'American Circus', Decimal('4.99'), 3, 2006),
 (22, 'Amistad Midsummer', Decimal('2.99'), 6, 2006),
 (23, 'Anaconda Confessions', Decimal('0.99'), 3, 2006),
 (24, 'Analyze Hoosiers', Decimal('2.99'), 6, 2006),
 (25, 'Angels Life', Decimal('2.99'), 3, 2006),
 (26, 'Annie Identity', Decimal('0.99'), 3, 2006),
 (27, 'Anonymous Human', Decimal('0.99'), 7, 2006),
 (28, 'Anthem Luke', Decimal('4.99'), 5, 2006),
 (29, 'Antitrust Tomatoes', Decimal('2.99'), 5, 2006),
 (30, 'Anything Savannah', Decimal('2.99'), 4, 2006),
 (31, 'Apache Divine', Decimal('4.99'), 5, 2006),
 (32, 'Apocalypse Flamingos', Decimal('4.99'), 6, 2006),
 (33, 'Apollo Teen', Decimal('2.99'), 5, 2006),
 (34, 'Arabia Dogma', Decimal('0.99'), 6, 2006),
 (35, 'Arachnophobia Rollercoaster', Decimal('2.99'), 4, 2006),
 (36, 'Argonauts Town', Decimal('0.99'), 7, 2006),
 (37, 'Arizona Bang', Decimal('2.99'), 3, 2006),
 (38, 'Ark Ridgemont', Decimal('0.99'), 6, 2006),
 (39, 'Armageddon Lost', Decimal('0.99'), 5, 2006),
 (40, 'Army Flintstones', Decimal('0.99'), 4, 2006),
 (41, 'Arsenic Independence', Decimal('0.99'), 4, 2006),
 (42, 'Artist Coldblooded', Decimal('2.99'), 5, 2006),
 (265, 'Dying Maker', Decimal('4.99'), 5, 2006),
 (43, 'Atlantis Cause', Decimal('2.99'), 6, 2006),
 (44, 'Attacks Hate', Decimal('4.99'), 5, 2006),
 (45, 'Attraction Newton', Decimal('4.99'), 5, 2006),
 (46, 'Autumn Crow', Decimal('4.99'), 3, 2006),
 (47, 'Baby Hall', Decimal('4.99'), 5, 2006),
 (48, 'Backlash Undefeated', Decimal('4.99'), 3, 2006),
 (49, 'Badman Dawn', Decimal('2.99'), 6, 2006),
 (50, 'Baked Cleopatra', Decimal('2.99'), 3, 2006),
 (126, 'Casualties Encino', Decimal('4.99'), 3, 2006),
 (51, 'Balloon Homeward', Decimal('2.99'), 5, 2006),
 (52, 'Ballroom Mockingbird', Decimal('0.99'), 6, 2006),
 (53, 'Bang Kwai', Decimal('2.99'), 5, 2006),
 (54, 'Banger Pinocchio', Decimal('0.99'), 5, 2006),
 (55, 'Barbarella Streetcar', Decimal('2.99'), 6, 2006),
 (56, 'Barefoot Manchurian', Decimal('2.99'), 6, 2006),
 (57, 'Basic Easy', Decimal('2.99'), 4, 2006),
 (58, 'Beach Heartbreakers', Decimal('2.99'), 6, 2006),
 (59, 'Bear Graceland', Decimal('2.99'), 4, 2006),
 (60, 'Beast Hunchback', Decimal('4.99'), 3, 2006),
 (61, 'Beauty Grease', Decimal('4.99'), 5, 2006),
 (62, 'Bed Highball', Decimal('2.99'), 5, 2006),
 (63, 'Bedazzled Married', Decimal('0.99'), 6, 2006),
 (64, 'Beethoven Exorcist', Decimal('0.99'), 6, 2006),
 (65, 'Behavior Runaway', Decimal('4.99'), 3, 2006),
 (66, 'Beneath Rush', Decimal('0.99'), 6, 2006),
 (67, 'Berets Agent', Decimal('2.99'), 5, 2006),
 (68, 'Betrayed Rear', Decimal('4.99'), 5, 2006),
 (69, 'Beverly Outlaw', Decimal('2.99'), 3, 2006),
 (70, 'Bikini Borrowers', Decimal('4.99'), 7, 2006),
 (71, 'Bilko Anonymous', Decimal('4.99'), 3, 2006),
 (72, 'Bill Others', 

Argh! We get films with rental rates other than 4.99! What's gone wrong? We need to worry about the order of evaluation. We want the `OR` operation to execute **before** the `AND` operation, and we enforce this by use of parentheses!


In [11]:
%%sql

SELECT film_id, title, rental_rate, rental_duration, release_year
FROM film 
WHERE rental_rate = 4.99 AND (rental_duration <= 3 OR release_year = 2006)

 * postgresql://postgres:***@localhost/dvdrental
336 rows affected.


[(133, 'Chamber Italian', Decimal('4.99'), 7, 2006),
 (384, 'Grosse Wonderful', Decimal('4.99'), 5, 2006),
 (8, 'Airport Pollock', Decimal('4.99'), 6, 2006),
 (98, 'Bright Encounters', Decimal('4.99'), 4, 2006),
 (2, 'Ace Goldfinger', Decimal('4.99'), 3, 2006),
 (7, 'Airplane Sierra', Decimal('4.99'), 6, 2006),
 (10, 'Aladdin Calendar', Decimal('4.99'), 6, 2006),
 (13, 'Ali Forever', Decimal('4.99'), 4, 2006),
 (20, 'Amelie Hellfighters', Decimal('4.99'), 4, 2006),
 (21, 'American Circus', Decimal('4.99'), 3, 2006),
 (28, 'Anthem Luke', Decimal('4.99'), 5, 2006),
 (31, 'Apache Divine', Decimal('4.99'), 5, 2006),
 (32, 'Apocalypse Flamingos', Decimal('4.99'), 6, 2006),
 (265, 'Dying Maker', Decimal('4.99'), 5, 2006),
 (44, 'Attacks Hate', Decimal('4.99'), 5, 2006),
 (45, 'Attraction Newton', Decimal('4.99'), 5, 2006),
 (46, 'Autumn Crow', Decimal('4.99'), 3, 2006),
 (47, 'Baby Hall', Decimal('4.99'), 5, 2006),
 (48, 'Backlash Undefeated', Decimal('4.99'), 3, 2006),
 (126, 'Casualties Encino', Decimal('4.99'), 3, 2006),
 (60, 'Beast Hunchback', Decimal('4.99'), 3, 2006),
 (61, 'Beauty Grease', Decimal('4.99'), 5, 2006),
 (65, 'Behavior Runaway', Decimal('4.99'), 3, 2006),
 (68, 'Betrayed Rear', Decimal('4.99'), 5, 2006),
 (70, 'Bikini Borrowers', Decimal('4.99'), 7, 2006),
 (71, 'Bilko Anonymous', Decimal('4.99'), 3, 2006),
 (74, 'Birch Antitrust', Decimal('4.99'), 4, 2006),
 (75, 'Bird Independence', Decimal('4.99'), 6, 2006),
 (77, 'Birds Perdition', Decimal('4.99'), 5, 2006),
 (81, 'Blindness Gun', Decimal('4.99'), 6, 2006),
 (84, 'Boiled Dares', Decimal('4.99'), 7, 2006),
 (86, 'Boogie Amelie', Decimal('4.99'), 6, 2006),
 (88, 'Born Spinal', Decimal('4.99'), 7, 2006),
 (92, 'Bowfinger Gables', Decimal('4.99'), 7, 2006),
 (93, 'Brannigan Sunrise', Decimal('4.99'), 4, 2006),
 (95, 'Breakfast Goldfinger', Decimal('4.99'), 5, 2006),
 (100, 'Brooklyn Desert', Decimal('4.99'), 7, 2006),
 (102, 'Bubble Grosse', Decimal('4.99'), 4, 2006),
 (103, 'Bucket Brotherhood', Decimal('4.99'), 7, 2006),
 (112, 'Calendar Gunfight', Decimal('4.99'), 4, 2006),
 (113, 'California Birds', Decimal('4.99'), 4, 2006),
 (117, 'Candles Grapes', Decimal('4.99'), 6, 2006),
 (120, 'Caribbean Liberty', Decimal('4.99'), 3, 2006),
 (123, 'Casablanca Super', Decimal('4.99'), 6, 2006),
 (124, 'Casper Dragonfly', Decimal('4.99'), 3, 2006),
 (127, 'Cat Coneheads', Decimal('4.99'), 5, 2006),
 (131, 'Center Dinosaur', Decimal('4.99'), 5, 2006),
 (134, 'Champion Flatliners', Decimal('4.99'), 4, 2006),
 (139, 'Chasing Fight', Decimal('4.99'), 7, 2006),
 (141, 'Chicago North', Decimal('4.99'), 6, 2006),
 (144, 'Chinatown Gladiator', Decimal('4.99'), 7, 2006),
 (145, 'Chisum Behavior', Decimal('4.99'), 5, 2006),
 (151, 'Cincinatti Whisperer', Decimal('4.99'), 5, 2006),
 (156, 'Clerks Angels', Decimal('4.99'), 3, 2006),
 (159, 'Closer Bang', Decimal('4.99'), 5, 2006),
 (161, 'Clue Grail', Decimal('4.99'), 6, 2006),
 (165, 'Coldblooded Darling', Decimal('4.99'), 7, 2006),
 (167, 'Coma Head', Decimal('4.99'), 6, 2006),
 (170, 'Command Darling', Decimal('4.99'), 5, 2006),
 (171, 'Commandments Express', Decimal('4.99'), 6, 2006),
 (172, 'Coneheads Smoochy', Decimal('4.99'), 7, 2006),
 (173, 'Confessions Maguire', Decimal('4.99'), 7, 2006),
 (174, 'Confidential Interview', Decimal('4.99'), 6, 2006),
 (177, 'Connecticut Tramp', Decimal('4.99'), 4, 2006),
 (179, 'Conquerer Nuts', Decimal('4.99'), 4, 2006),
 (182, 'Control Anthem', Decimal('4.99'), 7, 2006),
 (183, 'Conversation Downhill', Decimal('4.99'), 4, 2006),
 (190, 'Creepers Kane', Decimal('4.99'), 5, 2006),
 (192, 'Crossing Divorce', Decimal('4.99'), 4, 2006),
 (195, 'Crowds Telemark', Decimal('4.99'), 3, 2006),
 (202, 'Daddy Pittsburgh', Decimal('4.99'), 5, 2006),
 (203, 'Daisy Menagerie', Decimal('4.99'), 5, 2006),
 (207, 'Dangerous Uptown', Decimal('4.99'), 7, 2006),
 (210, 'Darko Dorado', Decimal('4.99'), 3, 2006),
 (211, 'Darling Breaking', Decimal('4.99'), 7, 2006),
 (212, 'Darn Forrester', Decimal('4.99'), 7, 2


That's better! Let's see a few more examples using `AND` and `OR`

> "Find all films with  rental duration between 3 and 5 hours inclusive".


In [13]:
%%sql

SELECT film_id, title, description
FROM film 
WHERE rental_duration >= 3 AND rental_duration <= 5

 * postgresql://postgres:***@localhost/dvdrental
597 rows affected.


[(384, 'Grosse Wonderful', 'A Epic Drama of a Cat And a Explorer who must Redeem a Moose in Australia'),
 (98, 'Bright Encounters', 'A Fateful Yarn of a Lumberjack And a Feminist who must Conquer a Student in A Jet Boat'),
 (2, 'Ace Goldfinger', 'A Astounding Epistle of a Database Administrator And a Explorer who must Find a Car in Ancient China'),
 (4, 'Affair Prejudice', 'A Fanciful Documentary of a Frisbee And a Lumberjack who must Chase a Monkey in A Shark Tank'),
 (6, 'Agent Truman', 'A Intrepid Panorama of a Robot And a Boy who must Escape a Sumo Wrestler in Ancient China'),
 (9, 'Alabama Devil', 'A Thoughtful Panorama of a Database Administrator And a Mad Scientist who must Outgun a Mad Scientist in A Jet Boat'),
 (213, 'Date Speed', 'A Touching Saga of a Composer And a Moose who must Discover a Dentist in A MySQL Convention'),
 (13, 'Ali Forever', 'A Action-Packed Drama of a Dentist And a Crocodile who must Battle a Feminist in The Canadian Rockies'),
 (15, 'Alien Center', 'A Brilliant Drama of a Cat And a Mad Scientist who must Battle a Feminist in A MySQL Convention'),
 (17, 'Alone Trip', 'A Fast-Paced Character Study of a Composer And a Dog who must Outgun a Boat in An Abandoned Fun House'),
 (20, 'Amelie Hellfighters', 'A Boring Drama of a Woman And a Squirrel who must Conquer a Student in A Baloon'),
 (21, 'American Circus', 'A Insightful Drama of a Girl And a Astronaut who must Face a Database Administrator in A Shark Tank'),
 (23, 'Anaconda Confessions', 'A Lacklusture Display of a Dentist And a Dentist who must Fight a Girl in Australia'),
 (25, 'Angels Life', 'A Thoughtful Display of a Woman And a Astronaut who must Battle a Robot in Berlin'),
 (26, 'Annie Identity', 'A Amazing Panorama of a Pastry Chef And a Boat who must Escape a Woman in An Abandoned Amusement Park'),
 (28, 'Anthem Luke', 'A Touching Panorama of a Waitress And a Woman who must Outrace a Dog in An Abandoned Amusement Park'),
 (29, 'Antitrust Tomatoes', 'A Fateful Yarn of a Womanizer And a Feminist who must Succumb a Database Administrator in Ancient India'),
 (30, 'Anything Savannah', 'A Epic Story of a Pastry Chef And a Woman who must Chase a Feminist in An Abandoned Fun House'),
 (31, 'Apache Divine', 'A Awe-Inspiring Reflection of a Pastry Chef And a Teacher who must Overcome a Sumo Wrestler in A U-Boat'),
 (33, 'Apollo Teen', 'A Action-Packed Reflection of a Crocodile And a Explorer who must Find a Sumo Wrestler in An Abandoned Mine Shaft'),
 (35, 'Arachnophobia Rollercoaster', 'A Action-Packed Reflection of a Pastry Chef And a Composer who must Discover a Mad Scientist in The First Manned Space Station'),
 (37, 'Arizona Bang', 'A Brilliant Panorama of a Mad Scientist And a Mad Cow who must Meet a Pioneer in A Monastery'),
 (39, 'Armageddon Lost', 'A Fast-Paced Tale of a Boat And a Teacher who must Succumb a Composer in An Abandoned Mine Shaft'),
 (40, 'Army Flintstones', 'A Boring Saga of a Database Administrator And a Womanizer who must Battle a Waitress in Nigeria'),
 (41, 'Arsenic Independence', 'A Fanciful Documentary of a Mad Cow And a Womanizer who must Find a Dentist in Berlin'),
 (42, 'Artist Coldblooded', 'A Stunning Reflection of a Robot And a Moose who must Challenge a Woman in California'),
 (265, 'Dying Maker', 'A Intrepid Tale of a Boat And a Monkey who must Kill a Cat in California'),
 (44, 'Attacks Hate', 'A Fast-Paced Panorama of a Technical Writer And a Mad Scientist who must Find a Feminist in An Abandoned Mine Shaft'),
 (45, 'Attraction Newton', 'A Astounding Panorama of a Composer And a Frisbee who must Reach a Husband in Ancient Japan'),
 (46, 'Autumn Crow', 'A Beautiful Tale of a Dentist And a Mad Cow who must Battle a Moose in The Sahara Desert'),
 (47, 'Baby Hall', 'A Boring Character Study of a A Shark And a Girl who must Outrace a Feminist in An Abandoned Mine Shaft'),
 (48, 'Backlash Undefeated', 'A Stunning Character Study of a Mad Scientist And a Mad Cow who must Kill a Car in A Monastery'),
 (50, 'Baked Cl

> "Find all films that were released in years other than 2006".


In [14]:
%%sql

SELECT film_id, title, description, release_year
FROM film 
WHERE release_year < '2006' OR release_year > '2006'

 * postgresql://postgres:***@localhost/dvdrental
0 rows affected.


[]

In [15]:
%%sql

SELECT * 
FROM film 
WHERE release_year != '2006' 

 * postgresql://postgres:***@localhost/dvdrental
0 rows affected.


[]

## `BETWEEN`, `NOT` and `IN`

The syntax in the last two examples is clumsy: it would be better to be able to define a range and then `SELECT` for records with fields in/not in that range. The `BETWEEN` keyword lets us do just that! 

Let's rewrite one of the previous queries using `BETWEEN`:

In [16]:
%%sql

SELECT film_id, title, description
FROM film 
WHERE rental_duration BETWEEN 3 AND  5 

 * postgresql://postgres:***@localhost/dvdrental
597 rows affected.


[(384, 'Grosse Wonderful', 'A Epic Drama of a Cat And a Explorer who must Redeem a Moose in Australia'),
 (98, 'Bright Encounters', 'A Fateful Yarn of a Lumberjack And a Feminist who must Conquer a Student in A Jet Boat'),
 (2, 'Ace Goldfinger', 'A Astounding Epistle of a Database Administrator And a Explorer who must Find a Car in Ancient China'),
 (4, 'Affair Prejudice', 'A Fanciful Documentary of a Frisbee And a Lumberjack who must Chase a Monkey in A Shark Tank'),
 (6, 'Agent Truman', 'A Intrepid Panorama of a Robot And a Boy who must Escape a Sumo Wrestler in Ancient China'),
 (9, 'Alabama Devil', 'A Thoughtful Panorama of a Database Administrator And a Mad Scientist who must Outgun a Mad Scientist in A Jet Boat'),
 (213, 'Date Speed', 'A Touching Saga of a Composer And a Moose who must Discover a Dentist in A MySQL Convention'),
 (13, 'Ali Forever', 'A Action-Packed Drama of a Dentist And a Crocodile who must Battle a Feminist in The Canadian Rockies'),
 (15, 'Alien Center', 'A Brilliant Drama of a Cat And a Mad Scientist who must Battle a Feminist in A MySQL Convention'),
 (17, 'Alone Trip', 'A Fast-Paced Character Study of a Composer And a Dog who must Outgun a Boat in An Abandoned Fun House'),
 (20, 'Amelie Hellfighters', 'A Boring Drama of a Woman And a Squirrel who must Conquer a Student in A Baloon'),
 (21, 'American Circus', 'A Insightful Drama of a Girl And a Astronaut who must Face a Database Administrator in A Shark Tank'),
 (23, 'Anaconda Confessions', 'A Lacklusture Display of a Dentist And a Dentist who must Fight a Girl in Australia'),
 (25, 'Angels Life', 'A Thoughtful Display of a Woman And a Astronaut who must Battle a Robot in Berlin'),
 (26, 'Annie Identity', 'A Amazing Panorama of a Pastry Chef And a Boat who must Escape a Woman in An Abandoned Amusement Park'),
 (28, 'Anthem Luke', 'A Touching Panorama of a Waitress And a Woman who must Outrace a Dog in An Abandoned Amusement Park'),
 (29, 'Antitrust Tomatoes', 'A Fateful Yarn of a Womanizer And a Feminist who must Succumb a Database Administrator in Ancient India'),
 (30, 'Anything Savannah', 'A Epic Story of a Pastry Chef And a Woman who must Chase a Feminist in An Abandoned Fun House'),
 (31, 'Apache Divine', 'A Awe-Inspiring Reflection of a Pastry Chef And a Teacher who must Overcome a Sumo Wrestler in A U-Boat'),
 (33, 'Apollo Teen', 'A Action-Packed Reflection of a Crocodile And a Explorer who must Find a Sumo Wrestler in An Abandoned Mine Shaft'),
 (35, 'Arachnophobia Rollercoaster', 'A Action-Packed Reflection of a Pastry Chef And a Composer who must Discover a Mad Scientist in The First Manned Space Station'),
 (37, 'Arizona Bang', 'A Brilliant Panorama of a Mad Scientist And a Mad Cow who must Meet a Pioneer in A Monastery'),
 (39, 'Armageddon Lost', 'A Fast-Paced Tale of a Boat And a Teacher who must Succumb a Composer in An Abandoned Mine Shaft'),
 (40, 'Army Flintstones', 'A Boring Saga of a Database Administrator And a Womanizer who must Battle a Waitress in Nigeria'),
 (41, 'Arsenic Independence', 'A Fanciful Documentary of a Mad Cow And a Womanizer who must Find a Dentist in Berlin'),
 (42, 'Artist Coldblooded', 'A Stunning Reflection of a Robot And a Moose who must Challenge a Woman in California'),
 (265, 'Dying Maker', 'A Intrepid Tale of a Boat And a Monkey who must Kill a Cat in California'),
 (44, 'Attacks Hate', 'A Fast-Paced Panorama of a Technical Writer And a Mad Scientist who must Find a Feminist in An Abandoned Mine Shaft'),
 (45, 'Attraction Newton', 'A Astounding Panorama of a Composer And a Frisbee who must Reach a Husband in Ancient Japan'),
 (46, 'Autumn Crow', 'A Beautiful Tale of a Dentist And a Mad Cow who must Battle a Moose in The Sahara Desert'),
 (47, 'Baby Hall', 'A Boring Character Study of a A Shark And a Girl who must Outrace a Feminist in An Abandoned Mine Shaft'),
 (48, 'Backlash Undefeated', 'A Stunning Character Study of a Mad Scientist And a Mad Cow who must Kill a Car in A Monastery'),
 (50, 'Baked Cl

We can also check for the opposite using `NOT`

In [17]:
%%sql

SELECT * 
FROM film 
WHERE rental_duration NOT BETWEEN 3 AND  5

 * postgresql://postgres:***@localhost/dvdrental
403 rows affected.


[(133, 'Chamber Italian', 'A Fateful Reflection of a Moose And a Husband who must Overcome a Monkey in Nigeria', 2006, 1, 7, Decimal('4.99'), 117, Decimal('14.99'), 'NC-17', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers'], "'chamber':1 'fate':4 'husband':11 'italian':2 'monkey':16 'moos':8 'must':13 'nigeria':18 'overcom':14 'reflect':5"),
 (8, 'Airport Pollock', 'A Epic Tale of a Moose And a Girl who must Confront a Monkey in Ancient India', 2006, 1, 6, Decimal('4.99'), 54, Decimal('15.99'), 'R', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers'], "'airport':1 'ancient':18 'confront':14 'epic':4 'girl':11 'india':19 'monkey':16 'moos':8 'must':13 'pollock':2 'tale':5"),
 (1, 'Academy Dinosaur', 'A Epic Drama of a Feminist And a Mad Scientist who must Battle a Teacher in The Canadian Rockies', 2006, 1, 6, Decimal('0.99'), 86, Decimal('20.99'), 'PG', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Deleted Scenes', 'Behind the Scenes'], "'academi':1 'battl':15 'canadian':20 'dinosaur':2 'drama':5 'epic':4 'feminist':8 'mad':11 'must':14 'rocki':21 'scientist':12 'teacher':17"),
 (3, 'Adaptation Holes', 'A Astounding Reflection of a Lumberjack And a Car who must Sink a Lumberjack in A Baloon Factory', 2006, 1, 7, Decimal('2.99'), 50, Decimal('18.99'), 'NC-17', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Deleted Scenes'], "'adapt':1 'astound':4 'baloon':19 'car':11 'factori':20 'hole':2 'lumberjack':8,16 'must':13 'reflect':5 'sink':14"),
 (5, 'African Egg', 'A Fast-Paced Documentary of a Pastry Chef And a Dentist who must Pursue a Forensic Psychologist in The Gulf of Mexico', 2006, 1, 6, Decimal('2.99'), 130, Decimal('22.99'), 'G', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Deleted Scenes'], "'african':1 'chef':11 'dentist':14 'documentari':7 'egg':2 'fast':5 'fast-pac':4 'forens':19 'gulf':23 'mexico':25 'must':16 'pace':6 'pastri':10 'psychologist':20 'pursu':17"),
 (7, 'Airplane Sierra', 'A Touching Saga of a Hunter And a Butler who must Discover a Butler in A Jet Boat', 2006, 1, 6, Decimal('4.99'), 62, Decimal('28.99'), 'PG-13', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Deleted Scenes'], "'airplan':1 'boat':20 'butler':11,16 'discov':14 'hunter':8 'jet':19 'must':13 'saga':5 'sierra':2 'touch':4"),
 (10, 'Aladdin Calendar', 'A Action-Packed Tale of a Man And a Lumberjack who must Reach a Feminist in Ancient China', 2006, 1, 6, Decimal('4.99'), 63, Decimal('24.99'), 'NC-17', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Deleted Scenes'], "'action':5 'action-pack':4 'aladdin':1 'ancient':20 'calendar':2 'china':21 'feminist':18 'lumberjack':13 'man':10 'must':15 'pack':6 'reach':16 'tale':7"),
 (11, 'Alamo Videotape', 'A Boring Epistle of a Butler And a Cat who must Fight a Pastry Chef in A MySQL Convention', 2006, 1, 6, Decimal('0.99'), 126, Decimal('16.99'), 'G', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Commentaries', 'Behind the Scenes'], "'alamo':1 'bore':4 'butler':8 'cat':11 'chef':17 'convent':21 'epistl':5 'fight':14 'must':13 'mysql':20 'pastri':16 'videotap':2"),
 (12, 'Alaska Phantom', 'A Fanciful Saga of a Hunter And a Pastry Chef who must Vanquish a Boy in Australia', 2006, 1, 6, Decimal('0.99'), 136, Decimal('22.99'), 'PG', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Commentaries', 'Deleted Scenes'], "'alaska':1 'australia':19 'boy':17 'chef':12 'fanci':4 'hunter':8 'must':14 'pastri':11 'phantom':2 'saga':5 'vanquish':15"),
 (14, 'Alice Fantasia', 'A Emotional Drama of a A Shark And a Database Administrator who must Vanquish a Pioneer in Soviet Georgia', 2006, 1, 6, Decimal('0.99'), 94, Decimal('23.99'), 'NC-17', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Deleted Scenes', 'Behind the Scenes'], "'administr':13 'alic':1 'databas':12 'drama':5 'emot':4 'fantasia':2 'georgia':21 'must':15 'pioneer':18 'shark':9 'soviet':20 'vanquish':16"),
 (16, 'Alley Evoluti

Note these two points:

* the range defined by `BETWEEN` is **inclusive** of the end points. So, in the first example, records with `rental_duration` of exactly 3 or 5 will be selected
* we use the `NOT BETWEEN` combination in the second example to select all records with `rental_duration` not in the range (where, again, the end points are included in the range).


The `IN` operator helps us deal with discrete valued fields more efficiently. Consider:


> "Find whether the countries Spain, South Africa, Ireland or Germany are in our database"

The long-winded way to write this is

In [18]:
%%sql

SELECT *
FROM country
WHERE country = 'Spain' OR country = 'South Africa' OR country = 'Ireland' OR country = 'Germany'

 * postgresql://postgres:***@localhost/dvdrental
3 rows affected.


[(38, 'Germany', datetime.datetime(2006, 2, 15, 9, 44)),
 (85, 'South Africa', datetime.datetime(2006, 2, 15, 9, 44)),
 (87, 'Spain', datetime.datetime(2006, 2, 15, 9, 44))]

or using `IN`

In [19]:
%%sql

SELECT * 
FROM country 
WHERE country IN ('Spain', 'South Africa', 'Ireland', 'Germany')


 * postgresql://postgres:***@localhost/dvdrental
3 rows affected.


[(38, 'Germany', datetime.datetime(2006, 2, 15, 9, 44)),
 (85, 'South Africa', datetime.datetime(2006, 2, 15, 9, 44)),
 (87, 'Spain', datetime.datetime(2006, 2, 15, 9, 44))]

We can also use `NOT` with `IN`

> "Find all countries other than Finland, Argentina or Canada."


In [20]:
%%sql

SELECT * 
FROM country 
WHERE country NOT IN ('Finland', 'Argentina', 'Canada')

 * postgresql://postgres:***@localhost/dvdrental
106 rows affected.


[(1, 'Afghanistan', datetime.datetime(2006, 2, 15, 9, 44)),
 (2, 'Algeria', datetime.datetime(2006, 2, 15, 9, 44)),
 (3, 'American Samoa', datetime.datetime(2006, 2, 15, 9, 44)),
 (4, 'Angola', datetime.datetime(2006, 2, 15, 9, 44)),
 (5, 'Anguilla', datetime.datetime(2006, 2, 15, 9, 44)),
 (7, 'Armenia', datetime.datetime(2006, 2, 15, 9, 44)),
 (8, 'Australia', datetime.datetime(2006, 2, 15, 9, 44)),
 (9, 'Austria', datetime.datetime(2006, 2, 15, 9, 44)),
 (10, 'Azerbaijan', datetime.datetime(2006, 2, 15, 9, 44)),
 (11, 'Bahrain', datetime.datetime(2006, 2, 15, 9, 44)),
 (12, 'Bangladesh', datetime.datetime(2006, 2, 15, 9, 44)),
 (13, 'Belarus', datetime.datetime(2006, 2, 15, 9, 44)),
 (14, 'Bolivia', datetime.datetime(2006, 2, 15, 9, 44)),
 (15, 'Brazil', datetime.datetime(2006, 2, 15, 9, 44)),
 (16, 'Brunei', datetime.datetime(2006, 2, 15, 9, 44)),
 (17, 'Bulgaria', datetime.datetime(2006, 2, 15, 9, 44)),
 (18, 'Cambodia', datetime.datetime(2006, 2, 15, 9, 44)),
 (19, 'Cameroon', datetime.datetime(2006, 2, 15, 9, 44)),
 (21, 'Chad', datetime.datetime(2006, 2, 15, 9, 44)),
 (22, 'Chile', datetime.datetime(2006, 2, 15, 9, 44)),
 (23, 'China', datetime.datetime(2006, 2, 15, 9, 44)),
 (24, 'Colombia', datetime.datetime(2006, 2, 15, 9, 44)),
 (25, 'Congo, The Democratic Republic of the', datetime.datetime(2006, 2, 15, 9, 44)),
 (26, 'Czech Republic', datetime.datetime(2006, 2, 15, 9, 44)),
 (27, 'Dominican Republic', datetime.datetime(2006, 2, 15, 9, 44)),
 (28, 'Ecuador', datetime.datetime(2006, 2, 15, 9, 44)),
 (29, 'Egypt', datetime.datetime(2006, 2, 15, 9, 44)),
 (30, 'Estonia', datetime.datetime(2006, 2, 15, 9, 44)),
 (31, 'Ethiopia', datetime.datetime(2006, 2, 15, 9, 44)),
 (32, 'Faroe Islands', datetime.datetime(2006, 2, 15, 9, 44)),
 (34, 'France', datetime.datetime(2006, 2, 15, 9, 44)),
 (35, 'French Guiana', datetime.datetime(2006, 2, 15, 9, 44)),
 (36, 'French Polynesia', datetime.datetime(2006, 2, 15, 9, 44)),
 (37, 'Gambia', datetime.datetime(2006, 2, 15, 9, 44)),
 (38, 'Germany', datetime.datetime(2006, 2, 15, 9, 44)),
 (39, 'Greece', datetime.datetime(2006, 2, 15, 9, 44)),
 (40, 'Greenland', datetime.datetime(2006, 2, 15, 9, 44)),
 (41, 'Holy See (Vatican City State)', datetime.datetime(2006, 2, 15, 9, 44)),
 (42, 'Hong Kong', datetime.datetime(2006, 2, 15, 9, 44)),
 (43, 'Hungary', datetime.datetime(2006, 2, 15, 9, 44)),
 (44, 'India', datetime.datetime(2006, 2, 15, 9, 44)),
 (45, 'Indonesia', datetime.datetime(2006, 2, 15, 9, 44)),
 (46, 'Iran', datetime.datetime(2006, 2, 15, 9, 44)),
 (47, 'Iraq', datetime.datetime(2006, 2, 15, 9, 44)),
 (48, 'Israel', datetime.datetime(2006, 2, 15, 9, 44)),
 (49, 'Italy', datetime.datetime(2006, 2, 15, 9, 44)),
 (50, 'Japan', datetime.datetime(2006, 2, 15, 9, 44)),
 (51, 'Kazakstan', datetime.datetime(2006, 2, 15, 9, 44)),
 (52, 'Kenya', datetime.datetime(2006, 2, 15, 9, 44)),
 (53, 'Kuwait', datetime.datetime(2006, 2, 15, 9, 44)),
 (54, 'Latvia', datetime.datetime(2006, 2, 15, 9, 44)),
 (55, 'Liechtenstein', datetime.datetime(2006, 2, 15, 9, 44)),
 (56, 'Lithuania', datetime.datetime(2006, 2, 15, 9, 44)),
 (57, 'Madagascar', datetime.datetime(2006, 2, 15, 9, 44)),
 (58, 'Malawi', datetime.datetime(2006, 2, 15, 9, 44)),
 (59, 'Malaysia', datetime.datetime(2006, 2, 15, 9, 44)),
 (60, 'Mexico', datetime.datetime(2006, 2, 15, 9, 44)),
 (61, 'Moldova', datetime.datetime(2006, 2, 15, 9, 44)),
 (62, 'Morocco', datetime.datetime(2006, 2, 15, 9, 44)),
 (63, 'Mozambique', datetime.datetime(2006, 2, 15, 9, 44)),
 (64, 'Myanmar', datetime.datetime(2006, 2, 15, 9, 44)),
 (65, 'Nauru', datetime.datetime(2006, 2, 15, 9, 44)),
 (66, 'Nepal', datetime.datetime(2006, 2, 15, 9, 44)),
 (67, 'Netherlands', datetime.datetime(2006, 2, 15, 9, 44)),
 (68, 'New Zealand', datetime.datetime(2006, 2, 15, 9, 44)),
 (69, 'Nigeria', datetime.datetime(2006, 2, 15, 9, 44)),
 (70, 'North Korea', datetime.datetime(2006, 2, 15, 9, 44)),
 (71, 'Oman', datetime.datetime(2006, 2, 15, 9, 44)),
 (72, 'Pakistan', date

## `LIKE` and wildcards

Your manager comes to you and says

> "I was talking with a colleague about a movie last month, it was about a Crocodile in Space or something. I can't remember the  name exactly, I think it began 'Conne...' something. Can you find it?"

You can see we're dealing with an **inexact comparison** here. How do we do this? Using the `LIKE` operator with a **wildcard**.

In [21]:
%%sql

SELECT film_id, title, description
FROM film 
WHERE title LIKE 'Conne%'

 * postgresql://postgres:***@localhost/dvdrental
2 rows affected.


[(177, 'Connecticut Tramp', 'A Unbelieveable Drama of a Crocodile And a Mad Cow who must Reach a Dentist in A Shark Tank'),
 (178, 'Connection Microcosmos', 'A Fateful Documentary of a Crocodile And a Husband who must Face a Husband in The First Manned Space Station')]

Here are the wildcards we can use: 

| wildcard | meaning |
| --- | --- |
| _ | a single character |
| % | a collection of characters |


We can place wildcards **anywhere** inside the string in the condition:


> "Find all actors with last names containing the phrase 'ere' anywhere"

In [22]:
%%sql

SELECT * 
FROM actor
WHERE last_name LIKE '%ere%'

 * postgresql://postgres:***@localhost/dvdrental
3 rows affected.


[(41, 'Jodie', 'Degeneres', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (107, 'Gina', 'Degeneres', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (166, 'Nick', 'Degeneres', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000))]

> "Find all actors with a last name beginning with 'D'

In [26]:
%%sql

SELECT * 
FROM actor 
WHERE first_name ILIKE 'd%'

 * postgresql://postgres:***@localhost/dvdrental
7 rows affected.


[(18, 'Dan', 'Torn', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (56, 'Dan', 'Harris', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (59, 'Dustin', 'Tautou', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (95, 'Daryl', 'Wahlberg', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (116, 'Dan', 'Streep', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (129, 'Daryl', 'Crawford', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000)),
 (182, 'Debbie', 'Akroyd', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000))]

<blockquote class='task'>
<b>Task - 2 mins</b> Write a query using `LIKE` and wildcards to answer:

    
    "Find all actors having 'a' as the second letter of their first names."

<details>
<summary><b>Hint</b></summary>
You can use a '_' wildcard for the first letter of `first_name`.
</details>
<br>
<details>
<summary><b>Solution</b></summary>
%%sql
SELECT * 
FROM actor 
WHERE first_name LIKE '_a%'")

</details>
</blockquote>


`LIKE` distinguishes between capital and lower case letters. If we need a case-insensitive version, we can use `ILIKE`.


## `IS NULL`

> "We need to ensure our staff records are up-to-date. Find all the staff who do not have a picture in the system."

In [27]:
%%sql 

SELECT *
FROM staff
WHERE picture IS NULL 

 * postgresql://postgres:***@localhost/dvdrental
1 rows affected.


[(2, 'Jon', 'Stephens', 4, 'Jon.Stephens@sakilastaff.com', 2, True, 'Jon', '8cb2237d0679ca88db6464eac60da96345513964', datetime.datetime(2006, 5, 16, 16, 13, 11, 793280), None)]


We can also use the `NOT` operator here too: `IS NOT NULL` is a valid condition!


## Recap - Full query syntax

In summary, here are the different keyword components of a `SELECT` query, the order in which they must appear, and whether they are required or optional <br>

This table shows where we've got to:<br>

| Order | Keyword | Specifies | Required? |
| --- | --- |--- | --- |
| 1 | SELECT | Column to query | Yes |
| 2 | FROM | Table to query |  Yes |
| 3 | WHERE | Row-level filter | No |

<br>
while here's a look ahead at what's still to come:<br>

| Order | Keyword | Specifies | Required? |
| --- | --- |--- | --- |
| 5 | GROUP BY| Grouping for aggregates | No |
| 6 | HAVING | Group-level filter | No |
| 7 | ORDER BY | Sort order | No |
| 8 | LIMIT | How many records to return | No |




## Manipulating returned data

After we have applied conditions to filter data in a `SELECT` statement, we can also manipulate what is returned. The easiest way to do this is to limit the returned fields!

In [31]:
%%sql 

SELECT actor_id, first_name, last_name
FROM actor
WHERE last_update = '2013-05-26 14:47:57.620000'

 * postgresql://postgres:***@localhost/dvdrental
200 rows affected.


[(1, 'Penelope', 'Guiness'),
 (2, 'Nick', 'Wahlberg'),
 (3, 'Ed', 'Chase'),
 (4, 'Jennifer', 'Davis'),
 (5, 'Johnny', 'Lollobrigida'),
 (6, 'Bette', 'Nicholson'),
 (7, 'Grace', 'Mostel'),
 (8, 'Matthew', 'Johansson'),
 (9, 'Joe', 'Swank'),
 (10, 'Christian', 'Gable'),
 (11, 'Zero', 'Cage'),
 (12, 'Karl', 'Berry'),
 (13, 'Uma', 'Wood'),
 (14, 'Vivien', 'Bergen'),
 (15, 'Cuba', 'Olivier'),
 (16, 'Fred', 'Costner'),
 (17, 'Helen', 'Voight'),
 (18, 'Dan', 'Torn'),
 (19, 'Bob', 'Fawcett'),
 (20, 'Lucille', 'Tracy'),
 (21, 'Kirsten', 'Paltrow'),
 (22, 'Elvis', 'Marx'),
 (23, 'Sandra', 'Kilmer'),
 (24, 'Cameron', 'Streep'),
 (25, 'Kevin', 'Bloom'),
 (26, 'Rip', 'Crawford'),
 (27, 'Julia', 'Mcqueen'),
 (28, 'Woody', 'Hoffman'),
 (29, 'Alec', 'Wayne'),
 (30, 'Sandra', 'Peck'),
 (31, 'Sissy', 'Sobieski'),
 (32, 'Tim', 'Hackman'),
 (33, 'Milla', 'Peck'),
 (34, 'Audrey', 'Olivier'),
 (35, 'Judy', 'Dean'),
 (36, 'Burt', 'Dukakis'),
 (37, 'Val', 'Bolger'),
 (38, 'Tom', 'Mckellen'),
 (39, 'Goldie', 'Brody'),
 (40, 'Johnny', 'Cage'),
 (41, 'Jodie', 'Degeneres'),
 (42, 'Tom', 'Miranda'),
 (43, 'Kirk', 'Jovovich'),
 (44, 'Nick', 'Stallone'),
 (45, 'Reese', 'Kilmer'),
 (46, 'Parker', 'Goldberg'),
 (47, 'Julia', 'Barrymore'),
 (48, 'Frances', 'Day-Lewis'),
 (49, 'Anne', 'Cronyn'),
 (50, 'Natalie', 'Hopkins'),
 (51, 'Gary', 'Phoenix'),
 (52, 'Carmen', 'Hunt'),
 (53, 'Mena', 'Temple'),
 (54, 'Penelope', 'Pinkett'),
 (55, 'Fay', 'Kilmer'),
 (56, 'Dan', 'Harris'),
 (57, 'Jude', 'Cruise'),
 (58, 'Christian', 'Akroyd'),
 (59, 'Dustin', 'Tautou'),
 (60, 'Henry', 'Berry'),
 (61, 'Christian', 'Neeson'),
 (62, 'Jayne', 'Neeson'),
 (63, 'Cameron', 'Wray'),
 (64, 'Ray', 'Johansson'),
 (65, 'Angela', 'Hudson'),
 (66, 'Mary', 'Tandy'),
 (67, 'Jessica', 'Bailey'),
 (68, 'Rip', 'Winslet'),
 (69, 'Kenneth', 'Paltrow'),
 (70, 'Michelle', 'Mcconaughey'),
 (71, 'Adam', 'Grant'),
 (72, 'Sean', 'Williams'),
 (73, 'Gary', 'Penn'),
 (74, 'Milla', 'Keitel'),
 (75, 'Burt', 'Posey'),
 (76, 'Angelina', 'Astaire'),
 (77, 'Cary', 'Mcconaughey'),
 (78, 'Groucho', 'Sinatra'),
 (79, 'Mae', 'Hoffman'),
 (80, 'Ralph', 'Cruz'),
 (81, 'Scarlett', 'Damon'),
 (82, 'Woody', 'Jolie'),
 (83, 'Ben', 'Willis'),
 (84, 'James', 'Pitt'),
 (85, 'Minnie', 'Zellweger'),
 (143, 'River', 'Dean'),
 (86, 'Greg', 'Chaplin'),
 (87, 'Spencer', 'Peck'),
 (88, 'Kenneth', 'Pesci'),
 (89, 'Charlize', 'Dench'),
 (90, 'Sean', 'Guiness'),
 (91, 'Christopher', 'Berry'),
 (92, 'Kirsten', 'Akroyd'),
 (93, 'Ellen', 'Presley'),
 (94, 'Kenneth', 'Torn'),
 (95, 'Daryl', 'Wahlberg'),
 (96, 'Gene', 'Willis'),
 (97, 'Meg', 'Hawke'),
 (98, 'Chris', 'Bridges'),
 (99, 'Jim', 'Mostel'),
 (100, 'Spencer', 'Depp'),
 (101, 'Susan', 'Davis'),
 (102, 'Walter', 'Torn'),
 (103, 'Matthew', 'Leigh'),
 (104, 'Penelope', 'Cronyn'),
 (105, 'Sidney', 'Crowe'),
 (106, 'Groucho', 'Dunst'),
 (107, 'Gina', 'Degeneres'),
 (108, 'Warren', 'Nolte'),
 (109, 'Sylvester', 'Dern'),
 (110, 'Susan', 'Davis'),
 (111, 'Cameron', 'Zellweger'),
 (112, 'Russell', 'Bacall'),
 (113, 'Morgan', 'Hopkins'),
 (114, 'Morgan', 'Mcdormand'),
 (115, 'Harrison', 'Bale'),
 (116, 'Dan', 'Streep'),
 (117, 'Renee', 'Tracy'),
 (118, 'Cuba', 'Allen'),
 (119, 'Warren', 'Jackman'),
 (120, 'Penelope', 'Monroe'),
 (121, 'Liza', 'Bergman'),
 (122, 'Salma', 'Nolte'),
 (123, 'Julianne', 'Dench'),
 (124, 'Scarlett', 'Bening'),
 (125, 'Albert', 'Nolte'),
 (126, 'Frances', 'Tomei'),
 (127, 'Kevin', 'Garland'),
 (128, 'Cate', 'Mcqueen'),
 (129, 'Daryl', 'Crawford'),
 (130, 'Greta', 'Keitel'),
 (131, 'Jane', 'Jackman'),
 (132, 'Adam', 'Hopper'),
 (133, 'Richard', 'Penn'),
 (134, 'Gene', 'Hopkins'),
 (135, 'Rita', 'Reynolds'),
 (136, 'Ed', 'Mansfield'),
 (137, 'Morgan', 'Williams'),
 (138, 'Lucille', 'Dee'),
 (139, 'Ewan', 'Gooding'),
 (140, 'Whoopi', 'Hurt'),
 (141, 'Cate', 'Harris'),
 (142, 'Jada', 'Ryder'),
 (144, 'Angela', 'Witherspoon'),
 (145, 'Kim', 'Allen'),
 (146, 'Albert', 'Johansson'),
 (147, 'Fay', 'Winslet'),
 (148, 'Emily', 'Dee'),
 (149, 'Russell', 'Temple'),
 (150, '

So here we return only the `actor_id`, `first_name` and `last_name`.

SQL offers additional operators to manipulate the return.

## Aliases via `AS`

> “Can we get a list of all actors with their first and last names combined together into one field called full_name?”
    
**Column aliases** are the way to solve problems like these! We use the `CONCAT()` function to **concatenate** (this is just a fancy way of saying ‘join strings together’) each pair of names into the full name. We set up a column alias using `AS full_name` to store the concatenated strings.

In [33]:
%%sql
SELECT actor_id, first_name, last_name, CONCAT(first_name, ' ', last_name) AS full_name 
FROM actor

 * postgresql://postgres:***@localhost/dvdrental
200 rows affected.


[(1, 'Penelope', 'Guiness', 'Penelope Guiness'),
 (2, 'Nick', 'Wahlberg', 'Nick Wahlberg'),
 (3, 'Ed', 'Chase', 'Ed Chase'),
 (4, 'Jennifer', 'Davis', 'Jennifer Davis'),
 (5, 'Johnny', 'Lollobrigida', 'Johnny Lollobrigida'),
 (6, 'Bette', 'Nicholson', 'Bette Nicholson'),
 (7, 'Grace', 'Mostel', 'Grace Mostel'),
 (8, 'Matthew', 'Johansson', 'Matthew Johansson'),
 (9, 'Joe', 'Swank', 'Joe Swank'),
 (10, 'Christian', 'Gable', 'Christian Gable'),
 (11, 'Zero', 'Cage', 'Zero Cage'),
 (12, 'Karl', 'Berry', 'Karl Berry'),
 (13, 'Uma', 'Wood', 'Uma Wood'),
 (14, 'Vivien', 'Bergen', 'Vivien Bergen'),
 (15, 'Cuba', 'Olivier', 'Cuba Olivier'),
 (16, 'Fred', 'Costner', 'Fred Costner'),
 (17, 'Helen', 'Voight', 'Helen Voight'),
 (18, 'Dan', 'Torn', 'Dan Torn'),
 (19, 'Bob', 'Fawcett', 'Bob Fawcett'),
 (20, 'Lucille', 'Tracy', 'Lucille Tracy'),
 (21, 'Kirsten', 'Paltrow', 'Kirsten Paltrow'),
 (22, 'Elvis', 'Marx', 'Elvis Marx'),
 (23, 'Sandra', 'Kilmer', 'Sandra Kilmer'),
 (24, 'Cameron', 'Streep', 'Cameron Streep'),
 (25, 'Kevin', 'Bloom', 'Kevin Bloom'),
 (26, 'Rip', 'Crawford', 'Rip Crawford'),
 (27, 'Julia', 'Mcqueen', 'Julia Mcqueen'),
 (28, 'Woody', 'Hoffman', 'Woody Hoffman'),
 (29, 'Alec', 'Wayne', 'Alec Wayne'),
 (30, 'Sandra', 'Peck', 'Sandra Peck'),
 (31, 'Sissy', 'Sobieski', 'Sissy Sobieski'),
 (32, 'Tim', 'Hackman', 'Tim Hackman'),
 (33, 'Milla', 'Peck', 'Milla Peck'),
 (34, 'Audrey', 'Olivier', 'Audrey Olivier'),
 (35, 'Judy', 'Dean', 'Judy Dean'),
 (36, 'Burt', 'Dukakis', 'Burt Dukakis'),
 (37, 'Val', 'Bolger', 'Val Bolger'),
 (38, 'Tom', 'Mckellen', 'Tom Mckellen'),
 (39, 'Goldie', 'Brody', 'Goldie Brody'),
 (40, 'Johnny', 'Cage', 'Johnny Cage'),
 (41, 'Jodie', 'Degeneres', 'Jodie Degeneres'),
 (42, 'Tom', 'Miranda', 'Tom Miranda'),
 (43, 'Kirk', 'Jovovich', 'Kirk Jovovich'),
 (44, 'Nick', 'Stallone', 'Nick Stallone'),
 (45, 'Reese', 'Kilmer', 'Reese Kilmer'),
 (46, 'Parker', 'Goldberg', 'Parker Goldberg'),
 (47, 'Julia', 'Barrymore', 'Julia Barrymore'),
 (48, 'Frances', 'Day-Lewis', 'Frances Day-Lewis'),
 (49, 'Anne', 'Cronyn', 'Anne Cronyn'),
 (50, 'Natalie', 'Hopkins', 'Natalie Hopkins'),
 (51, 'Gary', 'Phoenix', 'Gary Phoenix'),
 (52, 'Carmen', 'Hunt', 'Carmen Hunt'),
 (53, 'Mena', 'Temple', 'Mena Temple'),
 (54, 'Penelope', 'Pinkett', 'Penelope Pinkett'),
 (55, 'Fay', 'Kilmer', 'Fay Kilmer'),
 (56, 'Dan', 'Harris', 'Dan Harris'),
 (57, 'Jude', 'Cruise', 'Jude Cruise'),
 (58, 'Christian', 'Akroyd', 'Christian Akroyd'),
 (59, 'Dustin', 'Tautou', 'Dustin Tautou'),
 (60, 'Henry', 'Berry', 'Henry Berry'),
 (61, 'Christian', 'Neeson', 'Christian Neeson'),
 (62, 'Jayne', 'Neeson', 'Jayne Neeson'),
 (63, 'Cameron', 'Wray', 'Cameron Wray'),
 (64, 'Ray', 'Johansson', 'Ray Johansson'),
 (65, 'Angela', 'Hudson', 'Angela Hudson'),
 (66, 'Mary', 'Tandy', 'Mary Tandy'),
 (67, 'Jessica', 'Bailey', 'Jessica Bailey'),
 (68, 'Rip', 'Winslet', 'Rip Winslet'),
 (69, 'Kenneth', 'Paltrow', 'Kenneth Paltrow'),
 (70, 'Michelle', 'Mcconaughey', 'Michelle Mcconaughey'),
 (71, 'Adam', 'Grant', 'Adam Grant'),
 (72, 'Sean', 'Williams', 'Sean Williams'),
 (73, 'Gary', 'Penn', 'Gary Penn'),
 (74, 'Milla', 'Keitel', 'Milla Keitel'),
 (75, 'Burt', 'Posey', 'Burt Posey'),
 (76, 'Angelina', 'Astaire', 'Angelina Astaire'),
 (77, 'Cary', 'Mcconaughey', 'Cary Mcconaughey'),
 (78, 'Groucho', 'Sinatra', 'Groucho Sinatra'),
 (79, 'Mae', 'Hoffman', 'Mae Hoffman'),
 (80, 'Ralph', 'Cruz', 'Ralph Cruz'),
 (81, 'Scarlett', 'Damon', 'Scarlett Damon'),
 (82, 'Woody', 'Jolie', 'Woody Jolie'),
 (83, 'Ben', 'Willis', 'Ben Willis'),
 (84, 'James', 'Pitt', 'James Pitt'),
 (85, 'Minnie', 'Zellweger', 'Minnie Zellweger'),
 (143, 'River', 'Dean', 'River Dean'),
 (86, 'Greg', 'Chaplin', 'Greg Chaplin'),
 (87, 'Spencer', 'Peck', 'Spencer Peck'),
 (88, 'Kenneth', 'Pesci', 'Kenneth Pesci'),
 (89, 'Charlize', 'Dench', 'Charlize Dench'),
 (90, 'Sean', 'Guiness', 'Sean Guiness'),
 (91, 'Christopher', 'Berry', 'Christopher Berry'),
 (92, 'Kirsten', 'Akroyd', 'Kirsten Akroyd'),
 (93, 

The new `full_name` column will be at the right of the output. We see a problem with this: some of the records could have single names for `full_name`, but this represents a problem with the underlying data. We could add in a `WHERE` clause to filter out these problem rows.

In [34]:
%%sql

SELECT *, CONCAT(first_name, ' ', last_name) AS full_name 
FROM actor 
WHERE first_name IS NOT NULL AND last_name IS NOT NULL

 * postgresql://postgres:***@localhost/dvdrental
200 rows affected.


[(1, 'Penelope', 'Guiness', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Penelope Guiness'),
 (2, 'Nick', 'Wahlberg', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Nick Wahlberg'),
 (3, 'Ed', 'Chase', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Ed Chase'),
 (4, 'Jennifer', 'Davis', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Jennifer Davis'),
 (5, 'Johnny', 'Lollobrigida', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Johnny Lollobrigida'),
 (6, 'Bette', 'Nicholson', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Bette Nicholson'),
 (7, 'Grace', 'Mostel', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Grace Mostel'),
 (8, 'Matthew', 'Johansson', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Matthew Johansson'),
 (9, 'Joe', 'Swank', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Joe Swank'),
 (10, 'Christian', 'Gable', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Christian Gable'),
 (11, 'Zero', 'Cage', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Zero Cage'),
 (12, 'Karl', 'Berry', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Karl Berry'),
 (13, 'Uma', 'Wood', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Uma Wood'),
 (14, 'Vivien', 'Bergen', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Vivien Bergen'),
 (15, 'Cuba', 'Olivier', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Cuba Olivier'),
 (16, 'Fred', 'Costner', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Fred Costner'),
 (17, 'Helen', 'Voight', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Helen Voight'),
 (18, 'Dan', 'Torn', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Dan Torn'),
 (19, 'Bob', 'Fawcett', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Bob Fawcett'),
 (20, 'Lucille', 'Tracy', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Lucille Tracy'),
 (21, 'Kirsten', 'Paltrow', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Kirsten Paltrow'),
 (22, 'Elvis', 'Marx', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Elvis Marx'),
 (23, 'Sandra', 'Kilmer', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Sandra Kilmer'),
 (24, 'Cameron', 'Streep', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Cameron Streep'),
 (25, 'Kevin', 'Bloom', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Kevin Bloom'),
 (26, 'Rip', 'Crawford', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Rip Crawford'),
 (27, 'Julia', 'Mcqueen', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Julia Mcqueen'),
 (28, 'Woody', 'Hoffman', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Woody Hoffman'),
 (29, 'Alec', 'Wayne', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Alec Wayne'),
 (30, 'Sandra', 'Peck', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Sandra Peck'),
 (31, 'Sissy', 'Sobieski', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Sissy Sobieski'),
 (32, 'Tim', 'Hackman', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Tim Hackman'),
 (33, 'Milla', 'Peck', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Milla Peck'),
 (34, 'Audrey', 'Olivier', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Audrey Olivier'),
 (35, 'Judy', 'Dean', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Judy Dean'),
 (36, 'Burt', 'Dukakis', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Burt Dukakis'),
 (37, 'Val', 'Bolger', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Val Bolger'),
 (38, 'Tom', 'Mckellen', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Tom Mckellen'),
 (39, 'Goldie', 'Brody', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Goldie Brody'),
 (40, 'Johnny', 'Cage', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Johnny Cage'),
 (41, 'Jodie', 'Degeneres', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Jodie Degeneres'),
 (42, 'Tom', 'Miranda', datetime.datetime(2013, 5, 26, 14, 47, 57, 620000), 'Tom Miranda'),
 (43, 'Kirk', 'Jovovich', datetime.datetime(2013, 5

It is good practise to use aliases when creating new columns or aggregate functions (which we will come onto soon) so that if someone else (including your future self!) uses your output that your column/result names have meaning.

## `DISTINCT()`

>“Our database may be out of date! After the recent restructuring, we should now have 16 film categories in the database. How many categories do film belong to at present in the database?”

How do we solve this problem? It’s not enough to simply return **all** the categories of the film, as there will be a large amount of duplication. Instead, we need the **unique** list of departments. The `DISTINCT()` function returns a unique list.

In [35]:
%%sql

SELECT DISTINCT(category_id), name
FROM category

 * postgresql://postgres:***@localhost/dvdrental
16 rows affected.


[(16, 'Travel'),
 (3, 'Children'),
 (11, 'Horror'),
 (6, 'Documentary'),
 (7, 'Drama'),
 (2, 'Animation'),
 (9, 'Foreign'),
 (8, 'Family'),
 (15, 'Sports'),
 (12, 'Music'),
 (1, 'Action'),
 (10, 'Games'),
 (5, 'Comedy'),
 (4, 'Classics'),
 (14, 'Sci-Fi'),
 (13, 'New')]

## Aggregate functions

> “How many actor registries where updated at 14:47:57 on 2013-05-26?”

The `COUNT()` aggregate function can help us with counting problems:

In [38]:
%%sql
SELECT COUNT(*) 
FROM actor 
WHERE last_update = '2013-05-26 14:47:57.620000' 

 * postgresql://postgres:***@localhost/dvdrental
1 rows affected.


[(200,)]

In addition to `COUNT()`, we have the following aggregate functions: 

function 	| purpose
---|---
`SUM()` |	sum of a column
`AVG()` |	average of a column
`MIN()` |	minimum value of a column
`MAX()` |	maximum value of a column

As mentioned above it's good practice to use an alias (using the `AS` function) to give meaning to the result, such as:

In [39]:
%%sql
SELECT COUNT(*) AS updated_on_2013
FROM actor 
WHERE last_update = '2013-05-26 14:47:57.620000' 

 * postgresql://postgres:***@localhost/dvdrental
1 rows affected.


[(200,)]

**Task - 5 mins** Design queries using aggregate functions and what you have learned so far to answer the following question:

"What are the maximum and minimum rental rating among all films?"

<br>
<details>
    <summary><b>Solution</b></summary>

   %%sql  SELECT MAX(rental_rate) AS max_rating
           FROM film
    
  %%sql SELECT MIN(rental_rate) AS min_rating
           FROM film   
   

    
    
  ### Could also do it in a single query:
    
  %%sql SELECT MAX(rental_rate) AS max_rating,
           MIN(rental_rate) AS min_rating
           FROM film
    
</details>

## Sorting by columns

The `ORDER BY` operator lets us **sort** the returns of queries, either in descending (`DESC`) or ascending (`ASC`) order. The `ORDER BY` operator and associated keywords **always comes after** any `WHERE` clause.

The `LIMIT` operator is a natural partner to `ORDER BY`: it lets us limit **how many** records are returned by a query.

So, we saw before the minimum and maximum rating of films in the database. Let's find out which film have those ratings using the new operators!


In [44]:
%%sql 

SELECT rental_rate AS lowest_rate
FROM film 
WHERE rental_rate IS NOT NULL 
ORDER BY rental_rate ASC 
LIMIT 1

 * postgresql://postgres:***@localhost/dvdrental
1 rows affected.


[(Decimal('0.99'),)]

In [47]:
%%sql 

SELECT title, rental_rate AS highest_rate
FROM film 
WHERE rental_rate IS NOT NULL 
ORDER BY rental_rate DESC 


 * postgresql://postgres:***@localhost/dvdrental
1000 rows affected.


[('French Holiday', Decimal('4.99')),
 ('Bucket Brotherhood', Decimal('4.99')),
 ('Frisco Forrest', Decimal('4.99')),
 ('Prejudice Oleander', Decimal('4.99')),
 ('Frontier Cabin', Decimal('4.99')),
 ('Poseidon Forever', Decimal('4.99')),
 ('Fugitive Maguire', Decimal('4.99')),
 ('Wyoming Storm', Decimal('4.99')),
 ('Pluto Oleander', Decimal('4.99')),
 ('Platoon Instinct', Decimal('4.99')),
 ('Galaxy Sweethearts', Decimal('4.99')),
 ('Games Bowfinger', Decimal('4.99')),
 ('Pity Bound', Decimal('4.99')),
 ('Trap Guys', Decimal('4.99')),
 ('Garden Island', Decimal('4.99')),
 ('Waterfront Deliverance', Decimal('4.99')),
 ('Pittsburgh Hunchback', Decimal('4.99')),
 ('Working Microcosmos', Decimal('4.99')),
 ('Ghost Groundhog', Decimal('4.99')),
 ('Pinocchio Simon', Decimal('4.99')),
 ('Trainspotting Strangers', Decimal('4.99')),
 ('Philadelphia Wife', Decimal('4.99')),
 ('Perdition Fargo', Decimal('4.99')),
 ('Gladiator Westward', Decimal('4.99')),
 ('Pelican Comforts', Decimal('4.99')),
 ('Train Bunch', Decimal('4.99')),
 ('Traffic Hobbit', Decimal('4.99')),
 ('Peak Forever', Decimal('4.99')),
 ('Trading Pinocchio', Decimal('4.99')),
 ('Gold River', Decimal('4.99')),
 ('Paycheck Wait', Decimal('4.99')),
 ('Paths Control', Decimal('4.99')),
 ('Calendar Gunfight', Decimal('4.99')),
 ('Goodfellas Salute', Decimal('4.99')),
 ('California Birds', Decimal('4.99')),
 ('Gosford Donnie', Decimal('4.99')),
 ('Graceland Dynamite', Decimal('4.99')),
 ('Tourist Pelican', Decimal('4.99')),
 ('Past Suicides', Decimal('4.99')),
 ('Chamber Italian', Decimal('4.99')),
 ('Park Citizen', Decimal('4.99')),
 ('Panther Reds', Decimal('4.99')),
 ('Wash Heavenly', Decimal('4.99')),
 ('Panky Submarine', Decimal('4.99')),
 ('War Notting', Decimal('4.99')),
 ('Grinch Massage', Decimal('4.99')),
 ('Panic Club', Decimal('4.99')),
 ('Outlaw Hanky', Decimal('4.99')),
 ('Groundhog Uncut', Decimal('4.99')),
 ('Gump Date', Decimal('4.99')),
 ('Opus Ice', Decimal('4.99')),
 ('Opposite Necklace', Decimal('4.99')),
 ('Candles Grapes', Decimal('4.99')),
 ('Guys Falcon', Decimal('4.99')),
 ('Torque Bound', Decimal('4.99')),
 ('Hall Cassidy', Decimal('4.99')),
 ('Titans Jerk', Decimal('4.99')),
 ('Caribbean Liberty', Decimal('4.99')),
 ('Wanda Chamber', Decimal('4.99')),
 ('Open African', Decimal('4.99')),
 ('Hanging Deep', Decimal('4.99')),
 ('Titanic Boondock', Decimal('4.99')),
 ('Hanover Galaxy', Decimal('4.99')),
 ('Casablanca Super', Decimal('4.99')),
 ('Casper Dragonfly', Decimal('4.99')),
 ('October Submarine', Decimal('4.99')),
 ('Nuts Ties', Decimal('4.99')),
 ('Harry Idaho', Decimal('4.99')),
 ('North Tequila', Decimal('4.99')),
 ('Haunted Antitrust', Decimal('4.99')),
 ('Nightmare Chill', Decimal('4.99')),
 ('Name Detective', Decimal('4.99')),
 ('Head Stranger', Decimal('4.99')),
 ('Heartbreakers Bright', Decimal('4.99')),
 ('Walls Artist', Decimal('4.99')),
 ('Heavenly Gun', Decimal('4.99')),
 ('Heavyweights Beast', Decimal('4.99')),
 ('Cat Coneheads', Decimal('4.99')),
 ('Ties Hunger', Decimal('4.99')),
 ('Ali Forever', Decimal('4.99')),
 ('Musketeers Wait', Decimal('4.99')),
 ('Muppet Mile', Decimal('4.99')),
 ('Movie Shakespeare', Decimal('4.99')),
 ('Thin Sagebrush', Decimal('4.99')),
 ('Holes Brannigan', Decimal('4.99')),
 ('Holiday Games', Decimal('4.99')),
 ('Hollow Jeopardy', Decimal('4.99')),
 ('Moonwalker Fool', Decimal('4.99')),
 ('Moonshine Cabin', Decimal('4.99')),
 ('Monsoon Cause', Decimal('4.99')),
 ('Home Pity', Decimal('4.99')),
 ('Model Fish', Decimal('4.99')),
 ('Center Dinosaur', Decimal('4.99')),
 ('Mod Secretary', Decimal('4.99')),
 ('Mission Zoolander', Decimal('4.99')),
 ('Thief Pelican', Decimal('4.99')),
 ('Champion Flatliners', Decimal('4.99')),
 ('Dying Maker', Decimal('4.99')),
 ('Wonderland Christmas', Decimal('4.99')),
 ('Mine Titans', Decimal('4.99')),
 ('Hotel Happiness', Decimal('4.99')),
 ('Minds Truman', Decimal('4.99')),
 ('Attacks Hate', Decimal('4.99')),
 ('Attraction Newton', Decimal('4.99')),
 ('Hunchback Impossible'

You see above we had problems in ordering with `NULL`s in the column we're sorting on. We can either filter them out with a `WHERE` clause, as we did above, or we can use the operators `NULLS FIRST` or `NULLS LAST` to specify where to put them in the list of records. These operators are always placed immediately after `DESC` or `ASC` for the respective column.

Let's rewrite the queries above using these operators:


In [49]:
%%sql 

SELECT title, rental_rate 
FROM film 
ORDER BY rental_rate ASC NULLS FIRST
LIMIT 1

 * postgresql://postgres:***@localhost/dvdrental
1 rows affected.


[('Academy Dinosaur', Decimal('0.99'))]

In [ ]:
%%sql 

SELECT * 
FROM film 
ORDER BY rental_rate DESC NULLS LAST
LIMIT 1

Finally, we can perform **multi-level sorts** on two or more columns:


> "Order films by rental rate, highest first, and then alphabetically by film title." 


In [50]:
%%sql 
SELECT rental_rate, title
FROM film 
ORDER BY rental_rate DESC NULLS LAST, title ASC NULLS LAST

 * postgresql://postgres:***@localhost/dvdrental
1000 rows affected.


[(Decimal('4.99'), 'Ace Goldfinger'),
 (Decimal('4.99'), 'Airplane Sierra'),
 (Decimal('4.99'), 'Airport Pollock'),
 (Decimal('4.99'), 'Aladdin Calendar'),
 (Decimal('4.99'), 'Ali Forever'),
 (Decimal('4.99'), 'Amelie Hellfighters'),
 (Decimal('4.99'), 'American Circus'),
 (Decimal('4.99'), 'Anthem Luke'),
 (Decimal('4.99'), 'Apache Divine'),
 (Decimal('4.99'), 'Apocalypse Flamingos'),
 (Decimal('4.99'), 'Attacks Hate'),
 (Decimal('4.99'), 'Attraction Newton'),
 (Decimal('4.99'), 'Autumn Crow'),
 (Decimal('4.99'), 'Baby Hall'),
 (Decimal('4.99'), 'Backlash Undefeated'),
 (Decimal('4.99'), 'Beast Hunchback'),
 (Decimal('4.99'), 'Beauty Grease'),
 (Decimal('4.99'), 'Behavior Runaway'),
 (Decimal('4.99'), 'Betrayed Rear'),
 (Decimal('4.99'), 'Bikini Borrowers'),
 (Decimal('4.99'), 'Bilko Anonymous'),
 (Decimal('4.99'), 'Birch Antitrust'),
 (Decimal('4.99'), 'Bird Independence'),
 (Decimal('4.99'), 'Birds Perdition'),
 (Decimal('4.99'), 'Blindness Gun'),
 (Decimal('4.99'), 'Boiled Dares'),
 (Decimal('4.99'), 'Boogie Amelie'),
 (Decimal('4.99'), 'Born Spinal'),
 (Decimal('4.99'), 'Bowfinger Gables'),
 (Decimal('4.99'), 'Brannigan Sunrise'),
 (Decimal('4.99'), 'Breakfast Goldfinger'),
 (Decimal('4.99'), 'Bright Encounters'),
 (Decimal('4.99'), 'Brooklyn Desert'),
 (Decimal('4.99'), 'Bubble Grosse'),
 (Decimal('4.99'), 'Bucket Brotherhood'),
 (Decimal('4.99'), 'Calendar Gunfight'),
 (Decimal('4.99'), 'California Birds'),
 (Decimal('4.99'), 'Candles Grapes'),
 (Decimal('4.99'), 'Caribbean Liberty'),
 (Decimal('4.99'), 'Casablanca Super'),
 (Decimal('4.99'), 'Casper Dragonfly'),
 (Decimal('4.99'), 'Casualties Encino'),
 (Decimal('4.99'), 'Cat Coneheads'),
 (Decimal('4.99'), 'Center Dinosaur'),
 (Decimal('4.99'), 'Chamber Italian'),
 (Decimal('4.99'), 'Champion Flatliners'),
 (Decimal('4.99'), 'Chasing Fight'),
 (Decimal('4.99'), 'Chicago North'),
 (Decimal('4.99'), 'Chinatown Gladiator'),
 (Decimal('4.99'), 'Chisum Behavior'),
 (Decimal('4.99'), 'Cincinatti Whisperer'),
 (Decimal('4.99'), 'Clerks Angels'),
 (Decimal('4.99'), 'Closer Bang'),
 (Decimal('4.99'), 'Clue Grail'),
 (Decimal('4.99'), 'Coldblooded Darling'),
 (Decimal('4.99'), 'Coma Head'),
 (Decimal('4.99'), 'Command Darling'),
 (Decimal('4.99'), 'Commandments Express'),
 (Decimal('4.99'), 'Coneheads Smoochy'),
 (Decimal('4.99'), 'Confessions Maguire'),
 (Decimal('4.99'), 'Confidential Interview'),
 (Decimal('4.99'), 'Connecticut Tramp'),
 (Decimal('4.99'), 'Conquerer Nuts'),
 (Decimal('4.99'), 'Control Anthem'),
 (Decimal('4.99'), 'Conversation Downhill'),
 (Decimal('4.99'), 'Creepers Kane'),
 (Decimal('4.99'), 'Crossing Divorce'),
 (Decimal('4.99'), 'Crowds Telemark'),
 (Decimal('4.99'), 'Daddy Pittsburgh'),
 (Decimal('4.99'), 'Daisy Menagerie'),
 (Decimal('4.99'), 'Dangerous Uptown'),
 (Decimal('4.99'), 'Darko Dorado'),
 (Decimal('4.99'), 'Darling Breaking'),
 (Decimal('4.99'), 'Darn Forrester'),
 (Decimal('4.99'), 'Daughter Madigan'),
 (Decimal('4.99'), 'Dawn Pond'),
 (Decimal('4.99'), 'Day Unfaithful'),
 (Decimal('4.99'), 'Dazed Punk'),
 (Decimal('4.99'), 'Deep Crusade'),
 (Decimal('4.99'), 'Desert Poseidon'),
 (Decimal('4.99'), 'Desperate Trainspotting'),
 (Decimal('4.99'), 'Destiny Saturday'),
 (Decimal('4.99'), 'Details Packer'),
 (Decimal('4.99'), 'Devil Desire'),
 (Decimal('4.99'), 'Dogma Family'),
 (Decimal('4.99'), 'Doors President'),
 (Decimal('4.99'), 'Dorado Notting'),
 (Decimal('4.99'), 'Doubtfire Labyrinth'),
 (Decimal('4.99'), 'Dozen Lion'),
 (Decimal('4.99'), 'Dragonfly Strangers'),
 (Decimal('4.99'), 'Drifter Commandments'),
 (Decimal('4.99'), 'Driving Polish'),
 (Decimal('4.99'), 'Drop Waterfront'),
 (Decimal('4.99'), 'Dude Blindness'),
 (Decimal('4.99'), 'Durham Panky'),
 (Decimal('4.99'), 'Dying Maker'),
 (Decimal('4.99'), 'Eagles Panky'),
 (Decimal('4.99'), 'Early Home'),
 (Decimal('4.99'), 'Easy Gladiator'),
 (Decimal('4.99'), 'Edge Kissing'),
 (Decimal('4.99'), 'Element Freddy'),
 (Decimal('4.99'), 'Elephant Trojan'),
 (Decimal('4.99'), 'Elf Murder'),

## MODE

How do we get 'the most common' value in a field? In statistics, this would correspond to the **mode**, but ANSI SQL (the specification language) does not offer a `MODE()` aggregate function (although PostgreSQL does as of version 9.4). So we need a way round that in cases where we are asked to find the most commonly occuring records. For example if we were asked:


> "Find the film rate most common across the whole database."

We will use a combination of the functions we have learnt so far to do this. Let's first write a `SELECT` to find "the most common rating (`rental_rate`) across the whole database". Let's think about the steps involved:

1. filter out any film with null `rental_rate`
2. group films by `rental_rate`
3. count the number of films in each group
4. return the `rental_rate` of the group with the highest count

In [55]:
%%sql 

SELECT rental_rate AS mode
FROM film
WHERE rental_rate IS NOT NULL
GROUP BY rental_rate
ORDER BY COUNT(rental_rate) DESC
LIMIT 1


 * postgresql://postgres:***@localhost/dvdrental
1 rows affected.


[(Decimal('0.99'),)]

This is the most commonly rated score of `rental_rate` in the entire database. We will learn at the next sessionabout subqueries and so how to use our result above to return the films that have this rating. 


## Grouping records

Consider the following problem

> "Find the number of films with each rental duration available on the database." 


We could solve this manually, but it would be a real pain. First, we would need to get a list of the film types (we saw how to do this earlier using `DISTINCT`), and then write a query using a `COUNT()` aggregate with a `WHERE` clause specifying each type in turn, something like


In [56]:
%%sql 

SELECT COUNT(film_id) AS number_films
FROM film 
WHERE rental_duration = 3

 * postgresql://postgres:***@localhost/dvdrental
1 rows affected.


[(203,)]

and so on many more times for each rental duration. Annoying, and not very general code: we need to know all rental durations before we start! Thankfully, SQL gives us the `GROUP BY` operator to automate this!


## `GROUP BY`

In [57]:
%%sql

SELECT rental_duration, COUNT(film_id) AS number_films
FROM film
GROUP BY rental_duration

 * postgresql://postgres:***@localhost/dvdrental
5 rows affected.


[(4, 203), (6, 212), (7, 191), (3, 203), (5, 191)]

Yay, this looks more useful! Note what SQL has done here: it first **groups** records by a specified column (`rental_duration` in this case), and then applies the aggregate function (`COUNT()`) to **each group**.

Let's see another few examples of grouping in queries:


> How many ratings are there for each qualification?

In [58]:
%%sql

SELECT rental_rate, COUNT(film_id) AS number_ratings
FROM film
GROUP BY rental_rate

 * postgresql://postgres:***@localhost/dvdrental
3 rows affected.


[(Decimal('2.99'), 323), (Decimal('4.99'), 336), (Decimal('0.99'), 341)]

"How many actor names start with an E?" 


In [59]:
%%sql

SELECT first_name, COUNT(actor_id) AS number_actors
FROM actor
WHERE first_name LIKE 'E%'
GROUP BY first_name

 * postgresql://postgres:***@localhost/dvdrental
5 rows affected.


[('Ed', 3), ('Elvis', 1), ('Emily', 1), ('Ellen', 1), ('Ewan', 1)]

You'll see here that we are counting the `id` column. You will have seen earlier that we used `COUNT(*)` which counts all rows returned. The difference between the two if there are any NULLS in the column. 

Let's take a look at the difference using a column which has NULLS in the staff `picture` column:


In [60]:
%%sql

SELECT COUNT(picture)
FROM staff

 * postgresql://postgres:***@localhost/dvdrental
1 rows affected.


[(1,)]

In [61]:
%%sql

SELECT COUNT(*)
FROM staff

 * postgresql://postgres:***@localhost/dvdrental
1 rows affected.


[(2,)]

The difference in numbers comes because there are ? `NULL` entries for the `picture` column and so doing `COUNT(picture)` only returns the number of non-null `picture` entries. 


## `HAVING`

So far we've seen that the `WHERE` clause let's us filter **records**, but what if we wish to filter **groups** by some value of an aggregate function? This is where the `HAVING` operator comes in!

Imagine one of our earlier queries had been even more specific:


> Show the number of films where at least 130 people gave a rental rate of 2.99 or 4.99 and had a rental duration of 6 or higher

In [67]:
%%sql

SELECT rental_duration, COUNT(film_id) AS number_films
FROM film
WHERE rental_rate IN (2.99, 4.99) 
GROUP BY rental_duration
HAVING COUNT(film_id) >130


 * postgresql://postgres:***@localhost/dvdrental
4 rows affected.


[(4, 131), (6, 136), (7, 132), (5, 135)]

We've added in a `HAVING` clause **after** the `GROUP BY`, and notice that it filters using an **aggregate function** of a column of the original data.


# Recap - full query syntax

Now we've completed our discussion of query syntax, here are **all** the different components of a `SELECT` query, the order in which they must appear, and whether they are required or optional <br>

| Order | Keyword | Specifies | Required? |
| --- | --- |--- | --- |
| 1 | SELECT | Column to query | Yes |
| 2 | AS | Column alias | No |
| 3 | FROM | Table to query |  Yes |
| 4 | WHERE | Row-level filter | No |
| 5 | GROUP BY| Grouping for aggregates | No |
| 6 | HAVING | Group-level filter | No |
| 7 | ORDER BY | Sort order | No |
| 8 | LIMIT | How many records to return | No |

## Useful mnemonic for order of SQL

| Keyword | Mnemonic |
| --- | --- |
| SELECT | So |
| FROM | Few |
| WHERE | Workers
| GROUP BY| Go
| HAVING | Home
| ORDER BY | On Time

